### ISSUE TITLE
No module named pcapy

### ISSUE THREAD

**Issue by Maslor** [k4m4/kickthemout#10]
After cloning the repo and installing the requirements with pip (scapy, specifically), I try to run the program (both in normal and sudo mode) and this is what I get. Do you know what I'm doing wrong?

```
python kickthemout.py 
Traceback (most recent call last):
  File "kickthemout.py", line 12, in <module>
    import scan, spoof
  File "/Users/Maslor/Desktop/kickthemout/scan.py", line 9, in <module>
    import scapy.config, scapy.layers.l2, scapy.route, socket, math, errno
  File "/Users/Maslor/Desktop/kickthemout/lib/python2.7/site-packages/scapy/layers/l2.py", line 16, in <module>
    from scapy.ansmachine import *
  File "/Users/Maslor/Desktop/kickthemout/lib/python2.7/site-packages/scapy/ansmachine.py", line 14, in <module>
    from scapy.sendrecv import send,sendp,sniff
  File "/Users/Maslor/Desktop/kickthemout/lib/python2.7/site-packages/scapy/sendrecv.py", line 14, in <module>
    from scapy.arch.consts import DARWIN, FREEBSD
  File "/Users/Maslor/Desktop/kickthemout/lib/python2.7/site-packages/scapy/arch/__init__.py", line 79, in <module>
    from scapy.arch.pcapdnet import *
  File "/Users/Maslor/Desktop/kickthemout/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 328, in <module>
    import pcapy as pcap
ImportError: No module named pcapy

```

**Comment by k4m4** [comment]
Try doing `sudo pip install -r scapy`.

**Comment by Maslor** [comment]
`Could not open requirements file: [Errno 2] No such file or directory: 'scapy'`

**Comment by k4m4** [comment]
Sorry, there was a typo in the command I shared with you. I fixed it now. Please give it another shot and let me know what happens.

**Comment by Maslor** [comment]
`Requirement already satisfied: scapy in ./lib/python2.7/site-packages (from -r requirements.txt (line 1))`

I ran `pip install pcapy` and now, instead of complaining about the pcapy module, it's complaining about a dumbnet module.

**Comment by k4m4** [comment]
Try doing:
```
$ sudo pip uninstall scapy
$ sudo pip install scapy
```
What OS are you running?

**Comment by Maslor** [comment]
I'm running macOS Sierra version 10.12.2, python 2.7.13

After uninstalling and installing scapy I keep getting the pcapy module error. I installed the pcapy module and the message is as follows:

```
(kickthemout) Gabriels-MacBook-Pro:kickthemout Maslor$ python kickthemout.py 
Traceback (most recent call last):
  File "kickthemout.py", line 12, in <module>
    import scan, spoof
  File "/Users/Maslor/Desktop/kickthemout/scan.py", line 9, in <module>
    import scapy.config, scapy.layers.l2, scapy.route, socket, math, errno
  File "/Users/Maslor/Desktop/kickthemout/lib/python2.7/site-packages/scapy/layers/l2.py", line 16, in <module>
    from scapy.ansmachine import *
  File "/Users/Maslor/Desktop/kickthemout/lib/python2.7/site-packages/scapy/ansmachine.py", line 14, in <module>
    from scapy.sendrecv import send,sendp,sniff
  File "/Users/Maslor/Desktop/kickthemout/lib/python2.7/site-packages/scapy/sendrecv.py", line 14, in <module>
    from scapy.arch.consts import DARWIN, FREEBSD
  File "/Users/Maslor/Desktop/kickthemout/lib/python2.7/site-packages/scapy/arch/__init__.py", line 79, in <module>
    from scapy.arch.pcapdnet import *
  File "/Users/Maslor/Desktop/kickthemout/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 471, in <module>
    import dumbnet as dnet
ImportError: No module named dumbnet
```

**Comment by k4m4** [comment]
I see. Generally, there are quite a few issues when installing scapy on a Mac OS X. I would recommend doing `$ sudo pip uninstall scapy` and attempting to download it through homebrew: `$ brew install scapy`.

**Comment by Maslor** [comment]
Ok, I think I know what my problem is. It seems that non-linux distributions require installing libpcap and libdnet and their Python wrappers. 
But the brew version of scapy works, thanks!

**Comment by kanherepratik** [comment]
ImportError: No module named scapy.config.

please help...!!

**Comment by k4m4** [comment]
Hi there. It seems that you haven't installed the requirements. Try running: `$ sudo pip install -r requirements.txt`. What OS are you running? @kanherepratik

**Comment by thisisALPINE** [comment]
I'm having the same exact issue. I'm running on a MacOsX, El Capitan. I tried to `brew uninstall scapy`, then `brew install scapy`, but it keeps saying that the requirements are not satisfied.

**Comment by k4m4** [comment]
Generally, scapy raises quite a few issues when it comes to Mac OS. @thisisALPINE 
Try running the following:
```
$ pip uninstall scapy
$ brew uninstall scapy
$ brew install scapy
```

**Comment by k4m4** [comment]
### For **Mac OS X Installations** run the following:

```
Install Requirements:
----------------------
$ sudo pip install pcapy
$ brew install libdnet
$ brew install scapy
--> You might be asked to run some commands after executing the previous step.

Clone Repository:
------------------
$ git clone https://github.com/k4m4/kickthemout.git
$ cd kickthemout/
$ python kickthemout.py
```

**NOTE**: You need to have [**Homebrew**](http://brew.sh/) installed before downloading requirements.

**Comment by k4m4** [comment]
If you are running on Mac OS X, try the above solution & please let me know if the issue gets resolved. @thisisALPINE @kanherepratik @Maslor

**Comment by SentinelWarren** [comment]
@k4m4 ,you can't install a python module with brew sir!cause it won't  be installed  installed as a module! inspect brew won't even be able to install scary since its not in the formulae but in python/scapy tap.

**Comment by k4m4** [comment]
I've tested and confirmed that you can use brew to install both scapy and libdnet. @SentinelWarren

**Comment by xdavidhu** [comment]
@SentinelWarren You cant install python modules with brew. Take scapy for example.

**Comment by xdavidhu** [comment]
@SentinelWarren You can install python modules with brew. Take scapy for example.

**Comment by SentinelWarren** [comment]
sorry,i meant the module won't be on formulae but in `homebrew/python/scapy` tap so was supposed to be something like `brew install homebrew/python/scapy`

**Comment by k4m4** [comment]
That is correct. However, in some cases, `brew install scapy` works just fine. Otherwise, it will simply ask you to run a different command. @SentinelWarren

**Comment by gowrav** [comment]
Its apparently moved to a new tap > https://github.com/Homebrew/homebrew-python/pull/388
https://github.com/Homebrew/homebrew-core/pull/1106

**Comment by k4m4** [comment]
@gowrav `pcapy` doesn't seem to exist anymore on homebrew; use `pip` instead.
