### ISSUE TITLE
Won't Work

### ISSUE THREAD

**Issue by herohamp** [k4m4/kickthemout#100]
herohamp:kickthemout hamptonmoore$ sudo python kickthemout.py  ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.  If you still cannot resolve this error, please submit an issue here: 	https://github.com/k4m4/kickthemout/issues

**Comment by herohamp** [comment]
I think the issue is scapy as I get an error when I run
brew install libdnet scapy nmap

**Comment by herohamp** [comment]
herohamp:kickthemout hamptonmoore$ brew install libdnet scapy nmap
Updating Homebrew...
Error: No available formula with the name "scapy" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

**Comment by Gus74v** [comment]
I have the same problem like @herohamp

**Comment by k4m4** [comment]
Hi guys. We've updated the installation procedure. Please read the readme.md file for more info. Also, please follow the issue template when creating an issue. Thanks. @herohamp @Gus74v
