### ISSUE TITLE
MAC Address error while detecting the connections on the router

### ISSUE THREAD

**Issue by NyanSniper101** [k4m4/kickthemout#102]
I'm using Kali Linux 2 Rolling edition. KickThemOut used to work perfectly but recently it has started giving the error: "ERROR: Enter the MAC Address manually".
Even when then MAC address is entered manually, it gives another error saying "Something went wrong!".
I followed all the steps in the description, updates the program and also updated the requirements, but still the same error.
Sometimes it works perfectly, but many times it gives out this error.

Thanks for help in advance.

**Comment by k4m4** [comment]
Hi there. Please submit a new issue that follows the [**Issue Template**](https://github.com/k4m4/kickthemout/blob/master/.github/ISSUE_TEMPLATE.md). Thanks.
