### ISSUE TITLE
[Improvement] Allow to set kicked IP manually

### ISSUE THREAD

**Issue by liar666** [k4m4/kickthemout#106]
Hi,

The network at my work is the following: 30 people share a single FTTH line distributed through 4 wifi repeaters. Unfortunately, the network very poorly configured. I'm not sure why for the moment (is it because the 4 repeaters shared the exact same name and network configuration? And/or is there a vlan system in place?), but when I use nmap/kickthemout, I do not see all the machines on the network, only a subset. Also, very strangely, I do not see the machines that are physically closer to me (and thus supposed to connect through the same repeater as I do).
As a consequence, I cannot use kickthemout on a machine even if I know it is connected to the network and I know it's IP (since dhcp deamon distributes the same IPs to the sames machine/MAC day after day).

I'm almost sure it's possible to ARP-spoof (is it really what kickthemout does?) an IP even if it is not registered on the network.

So, would it be possible to add an option to kickthemout that would allow me to enter the IP I want  to kick?

**Comment by k4m4** [comment]
This has been implemented in v2.0. Thank you for your suggestion!
