### ISSUE TITLE
error: /usr/bin/python: No module named pip

### ISSUE THREAD

**Issue by omarbakeer** [k4m4/kickthemout#107]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

- **OS name & version**:  Linux 14.04 
- **Python version**:  both 2.7 and 3.5 
- **Scapy version**:  2.2.0 
- **Nmap version**:  6.40 

running this code:
`$ sudo python -m pip install -r requirements.txt `

gets me this error:
`/usr/bin/python: No module named pip`

 I know python 2.7 is required to run this command, but I already have it, now how can I solve that issue ?

**Comment by k4m4** [comment]
Hi there. Try running this: `$ sudo apt-get install python-pip`. Please let me know if this resolved your issue. Thanks.

**Comment by leo9722** [comment]
sorry i have the same problem and is not working with $ sudo apt-get install python-pip

**Comment by k4m4** [comment]
Could you be a little more specific? What's the error? @leo9722 
@omarbakeer Did my response work for you? Thanks.

**Comment by omarbakeer** [comment]
yes somehow @k4m4 
but still I get this error :  
```
File "kickthemout.py", line 13, in <module>
    import urllib2 as urllib
ImportError: No module named 'urllib2'
```
I'm working with Python : 3.5.2 and I think it's the problem , if you can tell me how to enable Python 2.7 and disable the 3.5- version, maybe it will work.

**Comment by k4m4** [comment]
Try running `$ sudo python2 kickthemout.py`. @omarbakeer

**Comment by omarbakeer** [comment]
@k4m4  it worked man (Y) thanks
