### ISSUE TITLE
Weird errors in scanning process

### ISSUE THREAD

**Issue by davidg0** [k4m4/kickthemout#11]
Hello dear developers, some weird error messages appeared after I typed "python kickthemout"
I'm using a mac computer with python 2.7 and scapy installed.
```
Traceback (most recent call last):
  File "kickthemout.py", line 302, in <module>
    scanNetwork()
  File "kickthemout.py", line 61, in scanNetwork
    hostsList = scan.scanNetwork()
  File "/Users/DAVID/kickthemout/scan.py", line 64, in scanNetwork
    return scan_and_print_neighbors(net, interface)
  File "/Users/DAVID/kickthemout/scan.py", line 30, in scan_and_print_neighbors
    ans, unans = scapy.layers.l2.arping(net, iface=interface, timeout=timeout, verbose=False)
  File "/Library/Python/2.7/site-packages/scapy/layers/l2.py", line 700, in arping
    filter="arp and arp[7] = 2", timeout=timeout, iface_hint=net, **kargs)
  File "/Library/Python/2.7/site-packages/scapy/sendrecv.py", line 378, in srp
    a,b=sndrcv(s ,x,*args,**kargs)
  File "/Library/Python/2.7/site-packages/scapy/sendrecv.py", line 133, in sndrcv
    r = pks.nonblock_recv()
  File "/Library/Python/2.7/site-packages/scapy/arch/pcapdnet.py", line 672, in nonblock_recv
    p = self.recv(MTU)
  File "/Library/Python/2.7/site-packages/scapy/arch/pcapdnet.py", line 653, in recv
    pkt = self.ins.next()
  File "/Library/Python/2.7/site-packages/scapy/arch/pcapdnet.py", line 390, in next
    s,us = h.getts()
AttributeError: 'NoneType' object has no attribute 'getts'
```

**Comment by songlunglinh** [comment]
ERROR: Gateway IP could not be obtained. Please enter IP manually.

kickthemout> Enter Gateway IP (e.g. 192.168.1.1): 192.168.1.254

but program is exit.
you can fix it?

**Comment by k4m4** [comment]
As I see it, there are no devices on your network. Weird. Let me look into this. Have you selected KickAllOff? @davidg0

**Comment by k4m4** [comment]
It seems that scapy hasn't been correctly installed & configured.
Please try running:
```
$ pip uninstall scapy
$ sudo pip install scapy
```

**Comment by kashkalik** [comment]
Hi Developers, I installed scapy , but when I try to run the script, it gives me the error

 "ERROR: Requirements have not been properly satisfied. Please try running:
$ sudo pip install -r requirements.txt
If you still get the same error, please submit an issue here:
https://github.com/k4m4/kickthemout/issues/
"

What could be the problem ? 

Thank you !

**Comment by k4m4** [comment]
What operating system are you running? @davidg0

**Comment by SentinelWarren** [comment]
@k4m4 @davidg0 module `pypcap` should also be installed

**Comment by SentinelWarren** [comment]
and @k4m4 When you run pip with sudo, you run setup.py with sudo. In other words, you run arbitrary Python code from the Internet as root.for example If someone puts up a malicious project on PyPI  and you install it, you give an attacker root access to your machine. Prior to some recent fixes to pip and PyPI, an attacker could also run a man in the middle attack to inject their code when you download a trustworthy project.

**Comment by xdavidhu** [comment]
@SentinelWarren Otherwise you may encounter permission issues. So its more suitable this way.

**Comment by SentinelWarren** [comment]
@xdavidhu on a Mac Os x (and linux) `pip` will install the modules just fine since python it will be installed with root, remember `pip` its just a manager for python, so Permission issues won't happen. also when it comes to the script it self, it should be run using `sudo` privileges!
