### ISSUE TITLE
Здравствуйте! При установке WiFi-Pumpkin ошибка !Что делать? Спасибо!struct.error: argument for 's' must be a string root@kali:~/WiFi-Pumpkin

### ISSUE THREAD

**Issue by qwe1232d** [k4m4/kickthemout#111]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**:

**Comment by qwe1232d** [comment]
Здравствуйте! При установке WiFi-Pumpkin ошибка !Что делать? Спасибо!struct.error: argument for 's' must be a string root@kali:~/WiFi-Pumpkin

**Comment by k4m4** [comment]
Hi there. KickThemOut is not part of the WiFi-Pumpkin repository. Try creating an issue [here](https://github.com/P0cL4bs/WiFi-Pumpkin/issues).
