### ISSUE TITLE
Errors installing Scapy on OS X

### ISSUE THREAD

**Issue by joel-carter** [k4m4/kickthemout#112]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**: Hi there, I've been trying to use this program however, I cannot install scapy as the directory is not found. I have read through previous issues but can still not get it to work.

**Comment by k4m4** [comment]
Hi there. Since you haven't provided us with the appropriate info and the exact error message, there's not much we can do to help you. Please enter all details asked for in the issue template. Thanks.

**Comment by k4m4** [comment]
Please provide us with all appropriate details, and re-open this issue when you do so. Thank you.
