### ISSUE TITLE
Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by denbuilder** [k4m4/kickthemout#114]
Hello I am using this program on Bash on Ubuntu on Windows using my wireless card. 

I get this error

root@DESKTOP-7BTVN1H:~/kickthemout# python kickthemout.py
Scanning your network, hang on...
ERROR: Gateway IP could not be obtained. Please enter IP manually.
kickthemout> Enter Gateway IP (e.g. 192.168.1.1): 10.103.132.1
ERROR: Default Interface MAC Address could not be obtained. Please enter MAC manually.
kickthemout> Enter MAC Address (MM:MM:MM:SS:SS:SS): 74-C6-3B-04-59-25
ERROR: Network scanning failed. Please check your requirements configuration.
root@DESKTOP-7BTVN1H:~/kickthemout#

I am using this script on my school wifi.

**Comment by ayush1252** [comment]
Is there any fix for this issue yet ?

**Comment by k4m4** [comment]
Hi there. KickThemOut has been developed to operate with Windows and Mac OS X operating systems. Windows is not within the compatibility range. I would suggest installing it in a Linux environment. Thanks!
