### ISSUE TITLE
Network scanning failed. Please check your requirements configuration.

### ISSUE THREAD

**Issue by Reveles** [k4m4/kickthemout#115]
Hi I'm on macOS Sierra, and after trying to fix my problem with the #issue54 I still can't make kickthemout work. Still says "Network scanning failed. Please check your requirements configuration."
Any help ?

**Comment by Wes974** [comment]
I found a fix for that, I uninstalled scapy and python-nmap and reinstalled them. To do so enter this command :

`sudo pip uninstall scapy python-nmap`

Be aware that for whatever reason you may have to use the `-H` flag like that `sudo -H pip uninstall scapy python-nmap` and may need to run this command twice.

After that just run `sudo pip install -r requirements.txt` and when relaunching kickthemout you should be good.
