### ISSUE TITLE
partial packet loss

### ISSUE THREAD

**Issue by Fairgrounds** [k4m4/kickthemout#117]
- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

- **OS name & version**: <Kali 2017.1-->
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: https://gist.github.com/anonymous/c31860f066150e3d450cb4339aa1c127
- **Description**: Thanks for making this, I'm learning a lot. Program semi-works for me, (when I ping Google's DNS servers from target host there is more packet loss than usual.) However the host can still connect to and use the internet.

**Comment by usama7628674** [comment]
This happens to me as well packets partially loss so victim can use different sites but at the same time 

internet speed becomes low but still you can surf.
I suggest you to use Morpheus-master.There is option in that software to drop all packets and it works pretty well.I used it and you can't open even Google.com

**Comment by Fairgrounds** [comment]
Thanks for the suggestion usama, checking it out now.

**Comment by k4m4** [comment]
Hi guys. Please check out my answer to [this issue](https://github.com/k4m4/kickthemout/issues/231). Thanks.
