### ISSUE TITLE
kickthemout troubles

### ISSUE THREAD

**Issue by unknownkillerdude** [k4m4/kickthemout#120]
as I was trying to use kickthemout the other day i had trouble using this command to open it 

cmd (sudo ./kickthemout.py)    i had even tried another one (sudo python kickthemout.py) 

and they both gave me this error message ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

please someone help me..

**Comment by ritiek** [comment]
Did you run `sudo pip install -r requirements.txt`?

**Comment by unknownkillerdude** [comment]
yes i did

**Comment by unknownkillerdude** [comment]
ill try again tho

**Comment by unknownkillerdude** [comment]
it came back with Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8jivzh__/scapy/

**Comment by unknownkillerdude** [comment]
can anyone else help?

**Comment by R3DDY97** [comment]
@unknownkillerdude 

try installing in python 2.7.11
not in python 3.x
Check ur python version once

**Comment by k4m4** [comment]
Hi there. As @R3DDY97, try running `$ pip2 install -r requirements.txt`. You can also find the solution to this issue [here](https://github.com/k4m4/kickthemout/issues/28). 
P.S. Please follow the issue template before submitting, next time.
