### ISSUE TITLE
ERROR: Requirements have not been satisfied properly.

### ISSUE THREAD

**Issue by foreignspy** [k4m4/kickthemout#123]
Hi,

I tried installing kickthemout on MacOs and it says "ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions." 

I have this problem when I ran "sudo pip install pcapy" 
The directory '/Users/COMPUTER NAME/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag

**Comment by k4m4** [comment]
Hi there. Please abide by the issue template when reporting an issue. Try following the new installation process on the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file. If you're still experiencing problems, please  re-open this issue. Thanks.
