### ISSUE TITLE
Can't run kickthemout.py

### ISSUE THREAD

**Issue by hieuhuynh93** [k4m4/kickthemout#126]
## Checklist for submitting an issue to `KickThemOut`:

- [x ] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x ] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x ] I am running the latest version of KickThemOut.

 

- **OS name & version**: macOS 10.12.6
- **Python version**: 2.7.13
- **Scapy version**: 2.3.3
- **Nmap version**: 7.60
- **Link of [Gist](https://gist.github.com/hieuhuynh93/57d9db38c8346947e34b5c79c26a1a5e)**: 

<br/ >

- **Description**: I can't run python kickthemeout.py. You can view the screenshot for details
[Screenshot](http://imgur.com/a/jr34Q)

Thanks

**Comment by biggersmilesj** [comment]
i am getting this same issue inform me after getting solved.

**Comment by hieuhuynh93** [comment]
I solved it. If you can't install scapy via brew, following my steps:

> $ cd /tmp
> $ wget --trust-server-names scapy.net   # or wget -O scapy.zip scapy.net
> $ unzip master
> $ cd scapy-master
> $ sudo python setup.py install'

DONE !

**Comment by k4m4** [comment]
Hi there @hieuhuynh93. 
Glad you managed to solve your issue. I will probably add your **scapy installation alternative** to the README file.
Thank you:)

**Comment by MaIsma** [comment]
Hey after i installed scapy manualy with cd /tmp etc ... now when i lunch the kikthemout script i dot this 
`sudo python kickthemout.py 
Traceback (most recent call last):
  File "kickthemout.py", line 478, in <module>
    defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 357, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: too many values to unpack`
any solutions ?
