### ISSUE TITLE
Requirements have not been satisfied properly.

### ISSUE THREAD

**Issue by biggersmilesj** [k4m4/kickthemout#127]
[http://imgur.com/a/5lJG9](url)

here is a image if issue which i am getting please help me to solve this out.

Thank You in advance.
```

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues
```

**Comment by hieuhuynh93** [comment]
Following these steps to solve it 
https://github.com/k4m4/kickthemout/issues/126#issuecomment-320682721

**Comment by k4m4** [comment]
Hi there. Have you followed the installation process in the README file? Thanks.

**Comment by hieuhuynh93** [comment]
> Hi there. Have you followed the installation process in the README file? Thanks.

Sorry, I followed it but I've faced the error with scapy package, I can't install it via brew, so I had to manually install it.

**Comment by k4m4** [comment]
Good to hear that. @hieuhuynh93 
@biggersmilesj If you are still experiencing problems, be sure to re-open the issue. Thanks!
