### ISSUE TITLE
How to install kickthemout on arch based systems?(Manjaro)

### ISSUE THREAD

**Issue by AJgotBeard** [k4m4/kickthemout#129]
1) Clone the repo in Home directory(or anywhere you like)
2) cd into the directory `cd ~/kickthemout` in my case
3) run `$ sudo -H python2 -m pip install -r requirements.txt `
4) enter the password
5) After installation completion
6) run `sudo python2 kickthemout.py`

Hope it helps.

**Comment by k4m4** [comment]
Thanks for the **Arch Linux installation guide** alternative! I will probably add it to the README file.

**Comment by AJgotBeard** [comment]
My Pleasure.
I was trying to make it work for quite a while.

**Comment by k4m4** [comment]
Arch Linux Installation guide added: [commit 4052724](https://github.com/k4m4/kickthemout/commit/4052724390b2189b66fe0a9931f5f70cec3a90b6)

**Comment by AJgotBeard** [comment]
Cool, but I don't see `python2` in the commit
