### ISSUE TITLE
NameError: global name 'Gen' is not defined

### ISSUE THREAD

**Issue by sakertooth** [k4m4/kickthemout#15]
I have an issue. KickThemOut asks me for my Gateway IP. I typed it in and it returns the following error. 

```
ERROR: Gateway IP could not be obtained. Please enter IP manually.

kickthemout> Enter Gateway IP (e.g. 192.168.1.1): 192.168.1.1
Traceback (most recent call last):
  File "kickthemout.py", line 302, in <module>
    scanNetwork()
  File "kickthemout.py", line 61, in scanNetwork
    hostsList = scan.scanNetwork()
  File "C:\PentestBox\bin\customtools\MyTools\kickthemout\scan.py", line 64, in scanNetwork
    return scan_and_print_neighbors(net, interface)
  File "C:\PentestBox\bin\customtools\MyTools\kickthemout\scan.py", line 30, in scan_and_print_neighbors
    ans, unans = scapy.layers.l2.arping(net, iface=interface, timeout=timeout, verbose=False)
  File "C:\PentestBox\base\python\Lib\site-packages\scapy\layers\l2.py", line 700, in arping
    filter="arp and arp[7] = 2", timeout=timeout, iface_hint=net, **kargs)
  File "C:\PentestBox\base\python\Lib\site-packages\scapy\sendrecv.py", line 378, in srp
    a,b=sndrcv(s ,x,*args,**kargs)
  File "C:\PentestBox\base\python\Lib\site-packages\scapy\arch\windows\compatibility.py", line 14, in sndrcv
    if not isinstance(pkt, Gen):
NameError: global name 'Gen' is not defined`
```

# NameError: global name 'Gen' is not defined - What does that mean? 

Info: - Running this on Windows NOT a Linux distribution
        - I reinstalled scapy multiple times
        - I feel like this is a error with not having libpcap and libdnet

**Comment by k4m4** [comment]
Generally speaking, KickThemOut is designed to be compatible with Linux and Mac OS X (Unix systems) only. I believe you can give it a shot. It should work actually, however, it hasn't been tested on Windows. Try installing dnet, pcap & scapy - you can attempt to download from [here](https://github.com/Kondziowy/scapy_win64). Let me know how it goes. @sakertooth

**Comment by sakertooth** [comment]
Is there possibly anyway to install dnet and pcap using pip?    Can't seen to install it straight on with the exe files.

**Comment by xdavidhu** [comment]
@sakertooth Do you have pywin32 and winpcap installed? Those are the minimum requirements for scapy.

Aditionally its possible that you will have to install other dependencies as well. Here you can find all of them:
[https://github.com/zlorb/scapy#install-applications](https://github.com/zlorb/scapy#install-applications)

**Comment by sakertooth** [comment]
Welp, finally came to a conclusion that you had to be running on Linux. It was worth a shot.
