### ISSUE TITLE
Are we not allowed to contribute to this Project?

### ISSUE THREAD

**Issue by SentinelWarren** [k4m4/kickthemout#16]
Earlier today i contribute to this project but instead by pull request was closed and by ideas where used, so am just asking if we are not allowed to contribute to this project, why is it here in first place? Thank you

**Comment by SentinelWarren** [comment]
Earlier today i contribute to this project but instead by pull request was closed and by ideas where used,so am just asking if we are not allowed to contribute to this project,why is it here in first place? Thank you

**Comment by k4m4** [comment]
Of course, everyone is welcome to contribute to KickTheOut. It's just that there were some changes we didn't want to make, in your last contribution. @SentinelWarren
