### ISSUE TITLE
Requirements not satisfied

### ISSUE THREAD

**Issue by Kistarcsa** [k4m4/kickthemout#21]
Hi!

After I pulled the code with 'git clone https://github.com/k4m4/kickthemout.git' and downloaded 'scapy' with pip ('pip install -r requirements.txt') I still get the following message:

$ pip install -r requirements.txt
Requirement already satisfied: scapy in c:\python27\lib\site-packages (from -r requirements.txt (line 1))

$ python kickthemout.py

ERROR: Requirements have not been properly satisfied. Please try running:
        $ sudo pip install -r requirements.txt

If you still get the same error, please submit an issue here:
        https://github.com/k4m4/kickthemout/issues

I am 100% sure scapy has been installed and I have the latest files.

**Comment by Kistarcsa** [comment]
The issue was that I did not opened the command line as an administrator.

**Comment by xdavidhu** [comment]
Try reinstalling scapy:

```
sudo pip uninstall scapy
sudo pip install scapy
```

Also which os are you running it on?

(btw are you hungarian? your name looks like that)

**Comment by tinmar33** [comment]
Try this:

https://dustin.li/2016/08/scapy-on-mac-os-x/

It works for me

**Comment by k4m4** [comment]
@Kistarcsa Please let us know if your issue has been resolved. Thanks.

**Comment by k4m4** [comment]
If this doesn't resolve your problem, try [this](https://github.com/k4m4/kickthemout/issues/10). Thanks!
