### ISSUE TITLE
The script doesn't launch "requirements have not been satisfied properly."

### ISSUE THREAD

**Issue by falbinosantos** [k4m4/kickthemout#228]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: macOS Sierra 10.12.16
- **Python version**: 2.7
- **Scapy version**: 2.7
- **Nmap version**: ????
- **Link of [Gist](https://gist.github.com/)**: https://gist.github.com/falbinosantos/8c40f44459674a9ef29dcd68767d89c0

<br/ >

- **Description**: I'm with a trouble... The script doesn't launch as you can see here: 

<img width="849" alt="captura de tela 2017-08-10 as 22 45 51" src="https://user-images.githubusercontent.com/30849495/29198816-b0973454-7e1d-11e7-8275-8ff9a48bb420.png">

ButI already installed all the requirements.

**Comment by k4m4** [comment]
Hi there. Have you followed the MacOS installation process located in the README file? @falbinosantos

**Comment by falbinosantos** [comment]
Yes I do. I included even the installation process on my gist https://gist.github.com/falbinosantos/8c40f44459674a9ef29dcd68767d89c0

**Comment by Clean6** [comment]
I am having the same problem

**Comment by k4m4** [comment]
Try the updated macOS installation guide. Let me know if it works. Thanks. @falbinosantos @Clean6

**Comment by falbinosantos** [comment]
@k4m4 , same problem here... 

```
Felipes-MacBook-Pro:~ Felipe$ cd kickthemout/
Felipes-MacBook-Pro:kickthemout Felipe$ sudo -H pip install -r requirements.txt
Password:
Requirement already satisfied: scapy in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: python-nmap in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Felipes-MacBook-Pro:kickthemout Felipe$ sudo python kickthemout.py

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Felipes-MacBook-Pro:kickthemout Felipe$
``` 

In truth I didn't realize what was update in the macOS installation guide. Thank you.
