### ISSUE TITLE
MacOS installation problem

### ISSUE THREAD

**Issue by extras3** [k4m4/kickthemout#232]
## Checklist for submitting an issue to `KickThemOut`:

- [ √] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [ ] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [ √] I am running the latest version of KickThemOut.

 

- **OS name & version**:  Mac OS X 10.11.6 
- **Python version**:  3.6.2 
- **Scapy version**: 2.3.2
- **Nmap version**: 7.60
- **Link of [Gist](https://gist.github.com/)**: 

Hi! I have been installing all requirements and installing them as a super user [sudo (command)] and when I run the program it shows me that "ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions." I have already read the "README" file and I have been following all of the instructions for my MacBook Air. Please fix this or tell me what I can do to fix it on my own (I like troubleshooting [when it works]).

Thanks a lot
![screen shot 2017-09-09 at 11 58 54 pm](https://user-images.githubusercontent.com/31807306/30243856-e53cdf24-95ba-11e7-80df-98236f20f636.png)

***Sorry for the bad resolution.

- **Description**: After installing all requirements the program doesn't run. Even if I run it as root. (Mac OS X 10.11.6)

**Comment by usama7628674** [comment]
try this
`git clone https://github.com/dugsong/libdnet.git`
`cd libdnet`
`./configure && make`
`cd python`
`python setup.py install`

**Comment by extras3** [comment]
It Worked!!! Thanks a lot!

**Comment by incognitoRepo** [comment]
hello mates, i just wanted to note this under a few keywords ["macos", "bytes", "bridge1"]. 
https://github.com/phaethon/kamene/issues/22#issue-108894780
i needed to uninstall netifaces. ill post it under one post of the other two keywords. thanks!
