### ISSUE TITLE
Throwing back error when trying to pip install the requirements

### ISSUE THREAD

**Issue by Remmysboy** [k4m4/kickthemout#234]
Ive been trying to run Kickthemout on my mac osx sierra 10.12.6. I did the command 

Alexs-MacBook-Pro:kickthemout-master alex.$ pip install -r requirements.txt

It came back with installing scapy and python nmap...... after installing it threw 

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/bq/p9gm04vx4nx9bcz6dlz9p4800000gq/T/pip-build-uliDcU/scapy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/bq/p9gm04vx4nx9bcz6dlz9p4800000gq/T/pip-TgunIZ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/bq/p9gm04vx4nx9bcz6dlz9p4800000gq/T/pip-build-uliDcU/scapy/
Alexs-MacBook-Pro:kickthemout-master alex.$

**Comment by k4m4** [comment]
Hi there. This error has to do with `pip` and not `KickThemOut`. Try running `sudo pip install setuptools --upgrade`. If this doesn't work, a google search should do the job.
