### ISSUE TITLE
Arch installation, scapy already installed.

### ISSUE THREAD

**Issue by DrDonkey** [k4m4/kickthemout#240]
-> yaourt kickthemout
1 aur/kickthemout-git 0.1.r104.ga2e0432-1 (1) (0.18)
    Kick devices off your network by performing an ARP Spoof attack.
==> Enter n° of packages to be installed (e.g., 1 2 3 or 1-3)
==> ---------------------------------------------------------
==> 1

==> Downloading kickthemout-git PKGBUILD from AUR...
x .SRCINFO
x PKGBUILD
kickthemout-git 0.1.r104.ga2e0432-1  (2017-11-11 12:28)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> n

==> kickthemout-git dependencies:
 - python2 (already installed)
 - git (already installed) [makedepend]
 - scapy (package found)
 - python2-nmap (building from AUR)

==> Continue building kickthemout-git ? [Y/n]
==> -----------------------------------------
==> y

==> Building and installing package
==> Install or build missing dependencies for kickthemout-git:
y[sudo] password for sl33py_b3ard: 
resolving dependencies...
looking for conflicting packages...

Packages (1) scapy-2.3.3-1

Total Installed Size:  7.42 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                         [############################################################] 100%
(1/1) checking package integrity                                                                       [############################################################] 100%
(1/1) loading package files                                                                            [############################################################] 100%
(1/1) checking for file conflicts                                                                      [############################################################] 100%
error: failed to commit transaction (conflicting files)
scapy: /usr/bin/UTscapy exists in filesystem
scapy: /usr/bin/scapy exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/__init__.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/__init__.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/all.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/all.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/ansmachine.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/ansmachine.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/__init__.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/__init__.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/common.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/common.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/consts.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/consts.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/linux.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/linux.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/pcapdnet.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/pcapdnet.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/solaris.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/solaris.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/unix.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/unix.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/windows/__init__.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/windows/__init__.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/windows/compatibility.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/windows/compatibility.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/winpcapy.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/arch/winpcapy.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/as_resolvers.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/as_resolvers.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/asn1/__init__.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/asn1/__init__.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/asn1/asn1.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/asn1/asn1.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/asn1/ber.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/asn1/ber.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/asn1/mib.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/asn1/mib.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/asn1fields.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/asn1fields.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/asn1packet.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/asn1packet.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/automaton.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/automaton.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/autorun.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/autorun.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/base_classes.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/base_classes.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/config.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/config.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/HomePlugAV.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/HomePlugAV.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/__init__.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/__init__.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/avs.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/avs.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/bgp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/bgp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/carp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/carp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/cdp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/cdp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/chdlc.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/chdlc.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/coap.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/coap.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/dtp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/dtp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/eigrp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/eigrp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/etherip.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/etherip.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/gsm_um.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/gsm_um.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/gtp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/gtp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/icmp_extensions.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/icmp_extensions.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/igmp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/igmp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/igmpv3.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/igmpv3.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ikev2.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ikev2.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/isis.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/isis.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ldp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ldp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/modbus.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/modbus.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/mpls.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/mpls.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/nsh.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/nsh.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/openflow.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/openflow.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/openflow3.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/openflow3.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ospf.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ospf.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/pnio.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/pnio.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/pnio_rtc.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/pnio_rtc.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ppi.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ppi.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ppi_cace.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ppi_cace.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ppi_geotag.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ppi_geotag.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ripng.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ripng.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/rsvp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/rsvp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/sebek.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/sebek.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/send.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/send.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/skinny.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/skinny.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/spbm.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/spbm.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ubberlogger.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/ubberlogger.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/vqp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/vqp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/vtp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/vtp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/wpa_eapol.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/contrib/wpa_eapol.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/dadict.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/dadict.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/data.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/data.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/error.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/error.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/fields.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/fields.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/__init__.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/__init__.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/all.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/all.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/bluetooth.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/bluetooth.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/clns.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/clns.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/dhcp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/dhcp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/dhcp6.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/dhcp6.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/dns.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/dns.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/dot11.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/dot11.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/gprs.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/gprs.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/hsrp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/hsrp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/inet.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/inet.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/inet6.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/inet6.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/ipsec.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/ipsec.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/ir.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/ir.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/isakmp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/isakmp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/l2.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/l2.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/l2tp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/l2tp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/llmnr.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/llmnr.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/lltd.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/lltd.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/mgcp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/mgcp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/mobileip.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/mobileip.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/netbios.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/netbios.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/netflow.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/netflow.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/ntp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/ntp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/pflog.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/pflog.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/ppp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/ppp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/radius.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/radius.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/rip.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/rip.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/rtp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/rtp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/sctp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/sctp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/skinny.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/skinny.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/smb.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/smb.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/snmp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/snmp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/tftp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/tftp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/tls/__init__.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/tls/__init__.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/tls/cert.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/tls/cert.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/tls/crypto/__init__.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/tls/crypto/__init__.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/tls/crypto/curves.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/tls/crypto/curves.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/tls/crypto/pkcs1.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/tls/crypto/pkcs1.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/vrrp.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/vrrp.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/vxlan.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/vxlan.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/x509.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/layers/x509.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/main.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/main.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/modules/__init__.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/modules/__init__.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/modules/nmap.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/modules/nmap.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/modules/p0f.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/modules/p0f.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/modules/queso.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/modules/queso.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/modules/voip.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/modules/voip.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/packet.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/packet.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/pipetool.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/pipetool.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/plist.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/plist.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/pton_ntop.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/pton_ntop.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/route.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/route.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/route6.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/route6.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/scapypipes.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/scapypipes.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/sendrecv.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/sendrecv.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/supersocket.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/supersocket.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/themes.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/themes.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/tools/UTscapy.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/tools/UTscapy.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/tools/__init__.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/tools/__init__.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/tools/check_asdis.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/tools/check_asdis.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/utils.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/utils.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/utils6.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/utils6.pyc exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/volatile.py exists in filesystem
scapy: /usr/lib/python2.7/site-packages/scapy/volatile.pyc exists in filesystem
scapy: /usr/share/man/man1/scapy.1.gz exists in filesystem
Errors occurred, no packages were upgraded.
==> Restart building kickthemout-git ? [y/N]
==> ----------------------------------------
==>

**Comment by k4m4** [comment]
Hi there @TheDumbKnight. Have you tried running `kickthemout.py`?

**Comment by TheDumbKnight** [comment]
it is not installed in the system(in /usr/bin) but I have the repo cloned in my home dir.
(the cloned version runs but doesn't seem like working, most of the time 0 hosts are up or if hosts found it would be still on(after cutting them).

**Comment by KnownAsDon** [comment]
@DrDonkey Just create a folder not to messup anything else and clone the repo in there. Than instead of typing python kickthemout.py you should type python2 kickthemout.py because on arch when you have installed python with bundle or some other pacage there is a high chance you have installed both python 3 and 2 and the deafult is 3 but the script is coded on python 2 and the 2 versions have many diffrences with each other which could cause the code not work. So just type 
`python2 kickthemout.py`.Hope i helped :)

**Comment by DrDonkey** [comment]
Sorry for not closing the issue. Solved a long time ago.
