### ISSUE TITLE
Mac Spoofing wont work

### ISSUE THREAD

**Issue by Farnsw** [k4m4/kickthemout#242]
after executing the individual or the all command the program shows the IPs but not the devices and it stops at the spoofing part, this is on mac and the python version is 2.7

**Comment by k4m4** [comment]
Hi there @Farnsw. Could you please follow the issue template and provide more information about your problem? Additionally, please upload a screenshot of your terminal. Thanks!

**Comment by k4m4** [comment]
Closing due to user inactivity.
