### ISSUE TITLE
Cant run kickthemout

### ISSUE THREAD

**Issue by MateOW** [k4m4/kickthemout#248]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [ ] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**: <!-- if I write python kickthemout.py    there is this message: ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.
But I wrote this before: root@BabaPC:~/kickthemout# sudo pip install -r requirements.txt
Requirement already satisfied: scapy-python3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: python-nmap in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: netifaces in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))>

**Comment by datboi6942** [comment]
kickthemout wont run when I try to i get this error:

oot@kali:~/kickthemout# python3 kickthemout.py

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy.config'

I have uninstalled and reinstalled multiple times with still no success. I have all requirements installed but yet it still wont run

**Comment by k4m4** [comment]
@MateOW, you are running Python 2.7 instead of Python 3. Please have a look at the README file for installation instructions. Thanks.
