### ISSUE TITLE
No module named 'scapy'

### ISSUE THREAD

**Issue by crashler** [k4m4/kickthemout#253]
Hi,
If i write "python3 kickthemout.py"  in terminal it doesn't work and it's written - Details: "no module named 'scapy'"
and if python kickthemout.py it says : "'errors' is an inavalid keyword argument for this function.
What's the problem, can u help me? 
P.S: for the first time it worked, after i reinstalled vm it doesn't?
Thans

**Comment by xdavidhu** [comment]
Hi!

Did you install the requirements? If not, make sure to follow the installation procedure here:
https://github.com/k4m4/kickthemout#installation

**Comment by crashler** [comment]
So, the first time as I said everything worked fine, without  this command - "sudo -H pip3 install -r requirements.txt", but now when i try this it says that pip3 command is not found

**Comment by k4m4** [comment]
@crashler Try running `sudo -H python3 -m pip install -r requirements.txt`.

**Comment by DFrenzy** [comment]
Im on debian, No module named pip

**Comment by k4m4** [comment]
@DFrenzy Here you go then: `sudo apt-get install python3-pip`

**Comment by SheesAli** [comment]
Thanks, this helped me. :)

**Comment by k4m4** [comment]
@SheesAli No problem. 
I assume this has now been solved. If anyone is still experiencing this problem, please re-open this issue. Thanks!

**Comment by 0rigin5** [comment]
I tried this i keep getting no module named pip

**Comment by 0rigin5** [comment]
Tried all steps

**Comment by NickWayans** [comment]
@k4m4 Hi, 
My Problem couldn't be solved with that. 
Actually i really did all the Steps, i checked many times the README, and i even did these Steps here which you have explained. But it's still not working.  
If i type: "sudo -H python3 -m pip install -r requirements.txt" i get then this error message here: 

"Collecting scapy-python3 (from -r requirements.txt (line 1))
  Using cached scapy-python3-0.23.tar.gz
Collecting python-nmap (from -r requirements.txt (line 2))
  Using cached python-nmap-0.6.1.tar.gz
Collecting netifaces (from -r requirements.txt (line 3))
  Downloading netifaces-0.10.6.tar.gz
Building wheels for collected packages: scapy-python3, python-nmap, netifaces
  Running setup.py bdist_wheel for scapy-python3 ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wp5wxx13/scapy-python3/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpa6j4gw3epip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for scapy-python3
  Running setup.py clean for scapy-python3
  Running setup.py bdist_wheel for python-nmap ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wp5wxx13/python-nmap/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp8_9gs8w2pip-wheel- --python-tag cp35:
  /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'bugtrack_url'
    warnings.warn(msg)
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for python-nmap
  Running setup.py clean for python-nmap
  Running setup.py bdist_wheel for netifaces ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wp5wxx13/netifaces/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpnm56bce3pip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for netifaces
  Running setup.py clean for netifaces
Failed to build scapy-python3 python-nmap netifaces
Installing collected packages: scapy-python3, python-nmap, netifaces
  Running setup.py install for scapy-python3 ... done
  Running setup.py install for python-nmap ... done
  Running setup.py install for netifaces ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wp5wxx13/netifaces/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-qbeg3gqr-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    checking for getifaddrs...found.
    checking for getnameinfo...found.
    checking for IPv6 socket IOCTLs...not found.
    checking for optional header files...netash/ash.h netatalk/at.h netax25/ax25.h neteconet/ec.h netipx/ipx.h netpacket/packet.h linux/irda.h linux/atm.h linux/llc.h linux/tipc.h linux/dn.h.
    checking whether struct sockaddr has a length field...no.
    checking which sockaddr_xxx structs are defined...at ax25 in in6 ipx un ash ec ll atmpvc atmsvc dn irda llc.
    checking for routing socket support...no.
    checking for sysctl(CTL_NET...) support...no.
    checking for netlink support...yes.
    will use netlink to read routing table
    building 'netifaces' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNETIFACES_VERSION=0.10.6 -DHAVE_GETIFADDRS=1 -DHAVE_GETNAMEINFO=1 -DHAVE_NETASH_ASH_H=1 -DHAVE_NETATALK_AT_H=1 -DHAVE_NETAX25_AX25_H=1 -DHAVE_NETECONET_EC_H=1 -DHAVE_NETIPX_IPX_H=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_LINUX_IRDA_H=1 -DHAVE_LINUX_ATM_H=1 -DHAVE_LINUX_LLC_H=1 -DHAVE_LINUX_TIPC_H=1 -DHAVE_LINUX_DN_H=1 -DHAVE_SOCKADDR_AT=1 -DHAVE_SOCKADDR_AX25=1 -DHAVE_SOCKADDR_IN=1 -DHAVE_SOCKADDR_IN6=1 -DHAVE_SOCKADDR_IPX=1 -DHAVE_SOCKADDR_UN=1 -DHAVE_SOCKADDR_ASH=1 -DHAVE_SOCKADDR_EC=1 -DHAVE_SOCKADDR_LL=1 -DHAVE_SOCKADDR_ATMPVC=1 -DHAVE_SOCKADDR_ATMSVC=1 -DHAVE_SOCKADDR_DN=1 -DHAVE_SOCKADDR_IRDA=1 -DHAVE_SOCKADDR_LLC=1 -DHAVE_PF_NETLINK=1 -I/usr/include/python3.5m -c netifaces.c -o build/temp.linux-x86_64-3.5/netifaces.o
    netifaces.c:1:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wp5wxx13/netifaces/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-qbeg3gqr-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-wp5wxx13/netifaces/
You are using pip version 8.1.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command."

Any Idea what i could do ? I am on Linux Mint Cinnamon 18.03
