### ISSUE TITLE
ERROR: Network scanning failed. Please check your requirements configuration.

### ISSUE THREAD

**Issue by stanix96** [k4m4/kickthemout#254]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **macOS High Sierra 10.13.1** 
- **python 3.6.4** 
- **Scapy 3.0.0** 

<br/ >

- Hey, i installed everything like it was explained. But then when i type in sudo python3 kickthemout.py -s i get an error:

ERROR: Network scanning failed. Please check your requirements configuration.

How can i fix this?

**Comment by k4m4** [comment]
Hi there @stanix96. Have you followed the appropriate macOS installation guide?

**Comment by stanix96** [comment]
Hey, yes.

i followed every single step in the installtion guide, everything is fine till i enter "sudo python3 kickthemout.py".

![bildschirmfoto 2018-02-20 um 11 25 27](https://user-images.githubusercontent.com/36637985/36418946-d5d22f70-1630-11e8-9c36-e5aa315ffbbb.png)

**Comment by k4m4** [comment]
Please run `sudo -H python3 -m pip uninstall -r requirements.txt`. Then re-install all requirements by executing `sudo -H python3 -m pip install -r requirements.txt` and send me the results. Thanks!

**Comment by stanix96** [comment]
Still not working

![bildschirmfoto 2018-02-20 um 13 11 11](https://user-images.githubusercontent.com/36637985/36423287-a11f5f28-163f-11e8-81a2-a5cf48b0a1a2.png)

**Comment by k4m4** [comment]
Please run `~/kickthemout ❯❯❯ git pull` and re-run the program (i.e. `~/kickthemout ❯❯❯ sudo python3 kickthemout.py`. You should now be able to see more info; please share these new details.

**Comment by stanix96** [comment]
![bildschirmfoto 2018-02-20 um 13 39 38](https://user-images.githubusercontent.com/36637985/36424428-8d65818e-1643-11e8-9ec6-c3583cb791f0.png)

**Comment by k4m4** [comment]
Try: `~ ❯❯❯ brew install nmap`.

**Comment by stanix96** [comment]
Yes it finally works!!

Thank you for the quick support! :)

**Comment by k4m4** [comment]
Glad to hear that! Let me know if there's anything else I can help you with.
