### ISSUE TITLE
KickThemOut Error: Details: No module named request

### ISSUE THREAD

**Issue by razercortex101** [k4m4/kickthemout#257]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: **Kali Linux 2018.1**
- **Python version**: **Python 3 Version: Python 3.6.4+ ; Python 2 (regular) Version: Python 2.7.14+**
- **Scapy version**: **Scapy 3.0.0**
- **Nmap version**: **Nmap 7.60**
- **Link of [Gist](https://gist.github.com/)**: **https://gist.github.com/razercortex101/247cd1521194f274d9c5ef1f98c1cb90**

<br/ >

- **Description**: I successfully cloned the kickthemout GitHub content via git and then I attempted to run the .py file via python3 using the command `python3 kickthemout.py`. It hanged and then I tried to instead use python2 via the command `python kickthemout.py`. It resulted in the following error `ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions. If you still cannot resolve this error, please submit an issue here:https://github.com/k4m4/kickthemout/issues`

Here is the rest of the output `Details: No module named request`. I have already ran `pip install request`. I am also running these commands as the root user.

**Comment by Syonagar** [comment]
root@debian:~/Documents/kickthemout# cd kickthemout/
bash: cd: kickthemout/: No such file or directory
root@debian:~/Documents/kickthemout# sudo -H pip3 install -r requirements.txt
sudo: pip3: command not found
root@debian:~/Documents/kickthemout# python kickthemout.py

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: 'errors' is an invalid keyword argument for this function
root@debian:~/Documents/kickthemout#

**Comment by razercortex101** [comment]
Wait a second, typed in sudo python3 kickthemout.py then pressed Ctrl+C then this came up

`ERROR: Gateway IP could not be obtained. Please enter IP manually.

kickthemout> Enter Gateway IP (e.g. 192.168.1.1): 192.168.1.1
Scanning your nEtwork, hang on...
ERROR: Default Gateway MAC Address could not be obtained. Please enter MAC manually.

kickthemout> Enter your gateway's MAC Address (MM:MM:MM:SS:SS:SS): Scanning your network hang on...`

**Comment by Syonagar** [comment]
not working either,,
please tell me the true way install kickthemout.
i follow ur steps one by one but cant

**Comment by razercortex101** [comment]
Finally, it worked!

**Comment by razercortex101** [comment]
I updated my system to fix.

**Comment by razercortex101** [comment]
close #257
