### ISSUE TITLE
No module named nmap

### ISSUE THREAD

**Issue by SolonRubens** [k4m4/kickthemout#258]
Hey k4m4,
I love your tool, it's very usefull and cool,
but now I cloned the tool with

`git clone https://hithub.com/k4m4/kickthemout/`

kali cloned it and if I want to start the kickthemout.py
there's a error with
No module named nmap

What can I do?

**Comment by matthieusb** [comment]
Have you followed the instructions on the README.md ?
You should install nmap through apt-get and install the python requirements, all is explained there (Take the Debian walkthrough).

**Comment by Devloger** [comment]
I don't think you guys do this right, cuz it works.

instead of running by
sudo python...
do
sudo python3...

should work

**Comment by k4m4** [comment]
If anyone is experiencing this issue, please make sure to download `nmap`, as stated in the readme file. Thanks.
