### ISSUE TITLE
Failed to execute tcpdump. Check it is installed and in the PATH

### ISSUE THREAD

**Issue by hunterx101** [k4m4/kickthemout#260]
Failed to execute tcpdump. Check it is installed and in the PATH

**Comment by Un1Gfn** [comment]
Please install tcpdump with your pacman/apt-get/yum/dnf/...

**Comment by k4m4** [comment]
As suggested by @Un1Gfn, please try installing `tcpdump`. If you are still experiencing a problem, please re-open this issue. Thanks!
