### ISSUE TITLE
plz!! help!!!!!

### ISSUE THREAD

**Issue by classer12271227** [k4m4/kickthemout#261]
ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy'

How can I fix this problem?
also I did "pip install -r requirements.txt"!!

I want to install "kickthemout" in kali linux 2017.2.

**Comment by k4m4** [comment]
Hi there @classer12271227. It seems that you haven't followed the correct installation steps. Please refer to the readme file for the appropriate instructions. If you still don't manage to resolve your problem, please re-open this issue. The installation process has been updated. Thanks!
