### ISSUE TITLE
scapy is now scapy3k

### ISSUE THREAD

**Issue by javier404** [k4m4/kickthemout#262]
-->scapy is now scapy3k
 

- **OS name & version**: 
- **Python version**: <!-
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**:

**Comment by k4m4** [comment]
Hi there @javier404. I noticed the amendment and it doesn't look like this affects our repo. You can still call `scapy` with `from scapy.all import *`. Thanks!
