### ISSUE TITLE
"Details: 'errors' is an invalid keyword argument for this function" UNABLE TO RESOLVE THIS ISSUE PLEASE HELP

### ISSUE THREAD

**Issue by 0rigin5** [k4m4/kickthemout#265]
## Checklist for submitting an issue to `KickThemOut`:

- [yes] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [yes] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [yes] I am running the latest version of KickThemOut.

 

- **OS name & version**: <linux>
- **Python version**:
- **Scapy version*
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**: so originally, after following all steps in the read me and running "python kickthemout.py" i had an error saying "no modules named nmap" now i solved that just now by running "sudo pip -r requirements.txt" or something along those lines. now after that im getting this error: 

"    ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: 'errors' is an invalid keyword argument for this function    "

now im completely confused. has anyone resolved this issue already? any help?

**Comment by k4m4** [comment]
Hi there. KickThemOut has recently migrated to Python 3. Please refer to the readme file for the new installation process. If you are still experiencing this same error, please re-open this issue. Thanks!

**Comment by N0va1** [comment]
orsubuu cuucu
