### ISSUE TITLE
please help it says i dont have installed the requariarments but i hav it still doesnt work

### ISSUE THREAD

**Issue by javier404** [k4m4/kickthemout#266]
## Checklist for submitting an issue to `KickThemOut`:

- [ ] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [ ] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [ ] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**:

**Comment by allen369369** [comment]
Same

**Comment by allen369369** [comment]
some one help. Package is broke.

**Comment by tryfontheo** [comment]
Did you make sure to run sudo python3 kickthemout.py? This isn't compatible with python 2.7

**Comment by allen369369** [comment]
Yes I have tryed over and over. I installed it from the lazykali script
then I tryed installing it strat to kali. I get this as the error.

root@lost:~/kickthemout# python3 kickthemout.py

ERROR: Requirements have not been satisfied properly. Please look at the
README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
    https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy'
root@lost:~/kickthemout#

**Comment by allen369369** [comment]
Problem salved, had to install:
root@lost:~# apt-get install python3-pip

**Comment by allen369369** [comment]
But the problem still is happening when trying to run it from the lazykali
script. this is the error

ERROR: Requirements have not been satisfied properly. Please look at the
README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
    https://github.com/k4m4/kickthemout/issues

Details: 'errors' is an invalid keyword argument for this function
Press any key to go back...

So i just have to run from bash shell. So i believe that it a problem with
the lazykali reading the files, probably do to updates/changes to the
configure files???

**Comment by k4m4** [comment]
Hi @allen369369. This is because `lscript` hasn't been updated to be compatible with the new Python 3 version of KickThemOut. Refer to the readme file for the latest installation process. If anyone is still experiencing this error, please open a new issue. Thanks!
