### ISSUE TITLE
Failed to execute tcpdump. Check it is installed and in the PATH

### ISSUE THREAD

**Issue by JackPatt1122** [k4m4/kickthemout#267]
When I type the command `sudo ./kickthemout.py` I get an error message saying "Failed to execute tcpdump. Check it is installed and in the PATH" 

How would I install or execute this!!
Need Help
Thank you

**Comment by k4m4** [comment]
Hi there @JackPatt1122. This is a duplicate of Issue #260. Try installing `tcpdump` and if you are still experiencing the same error, please re-open this issue. Thanks!
