### ISSUE TITLE
Kickthemout tool is showing : No module named 'scapy' 

### ISSUE THREAD

**Issue by ravinderlinux51** [k4m4/kickthemout#271]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [ ] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**:

**Comment by ravinderlinux51** [comment]
Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy'

**Comment by panhavad** [comment]
```
root@orcale:~/Desktop/kickthemout# sudo -H pip3 install -r requirements.txt
Requirement already satisfied: scapy-python3 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: python-nmap in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: netifaces in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 3))
root@orcale:~/Desktop/kickthemout# python3 kickthemout.py

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
        https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy'
```

**Comment by Deezloader** [comment]
Dev should change the installation tuto. 

~ ❯❯❯ sudo apt-get update && sudo apt-get install nmap

~ ❯❯❯ git clone https://github.com/k4m4/kickthemout.git

~ ❯❯❯ cd kickthemout/
~ ❯❯❯Sudo apt-get install python3-setuptools
~ ❯❯❯sudo easy_install3 pip
~ ❯❯❯sudo apt-get install python3-dev
~ ❯❯❯sudo pip3 install netifaces
~/kickthemout ❯❯❯ sudo -H pip3 install -r requirements.txt

~/kickthemout ❯❯❯ sudo python3 kickthemout.py


works well for me

**Comment by c9obvi** [comment]
hey @Deezloader I followed steps but not working still. Deleted and reinstalled nothing. I am on python 3.6 and says the setuptools is 
"Package python3-setuptools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-setuptools' has no installation candidate"

same for the rest of your steps. It attempts to search for the packages then returns that it could not do anything. Help please. Really liked using this program til the update haven't been able to use it.

**Comment by k4m4** [comment]
Hi there. This error isn't related in with `KickThemOut`. Try running `sudo apt-get install python3-setuptools`. If this doesn't work, a google search should do the job. Thanks.

**Comment by Kwazzer** [comment]
@Deezloader Man, thank you so mush, it works now, thank you again 🗡
