### ISSUE TITLE
error code

### ISSUE THREAD

**Issue by Pingzehao** [k4m4/kickthemout#276]
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Aq5X62/netifaces/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-UgZaVR-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Aq5X62/netifaces/

**Comment by k4m4** [comment]
Hi there @Pingzehao. This error has to do with `pip` and not `KickThemOut`. Try running `sudo pip install setuptools --upgrade`. If this doesn't work, a google search should do the job. Thanks!
