### ISSUE TITLE
ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

### ISSUE THREAD

**Issue by psyko59200** [k4m4/kickthemout#279]
Hi, I have everything installed and it marks me this error
Scapy 2.4.0
python 3.6.5
nmap 7.70

```
root@ANDROID:~/Bureau/kickthemout-master# sudo python3 kickthemout.py

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: 'No module named 'scapy
root@ANDROID:~/ Bureau/kickthemout-master# pip install -r requirements.txt
Requirement already satisfied: scapy-python3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: python-nmap in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: netifaces in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
```

**Comment by Aabhusan** [comment]
i am also facing same problem, please someone help me to get rid of this problem, as soon as possible.

**Comment by sandman4812av** [comment]
same problem :(

**Comment by psyko59200** [comment]
Hi can you go to https://github.com/k4m4/kickthemout/issues/279 we are
several to have the same problems


2018-04-10 10:21 GMT+02:00 zach carr <notifications@github.com>:

**Comment by psyko59200** [comment]
Hi have you find a solution?

**Comment by k4m4** [comment]
Hi there @psyko59200. Can you try using `pip3` instead of `pip`? Thanks and apologies for the late response.

**Comment by psyko59200** [comment]
sudo -H pip3 install -r requirements.txt
Requirement already satisfied: scapy-python3 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1)) (0.23)
Requirement already satisfied: python-nmap in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2)) (0.6.1)
Requirement already satisfied: netifaces in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 3)) (0.10.6)
matplotlib 2.1.1 requires backports.functools_lru_cache, which is not installed.
matplotlib 2.1.1 requires subprocess32, which is not installed.

**Comment by k4m4** [comment]
Have you downloaded `nmap`?

**Comment by psyko59200** [comment]
Yes

**Comment by k4m4** [comment]
Can you please uninstall and reinstall all dependencies exactly as they are stated in the readme file, pasting all the steps here? Thanks.

**Comment by psyko59200** [comment]
how about uninstall?

**Comment by psyko59200** [comment]
I just reinstall everything and always the same mistake

**Comment by Aabhusan** [comment]
There is same problem even after we use pip3 command instead of pip.

**Comment by psyko59200** [comment]
root@ANDROID:~/Documents/kickthemout-master# python kickthemout.py 

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: 'errors' is an invalid keyword argument for this function
root@ANDROID:~/Documents/kickthemout-master# python3 kickthemout.py 

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy'
root@ANDROID:~/Documents/kickthemout-master#

**Comment by psyko59200** [comment]
when  i do udo -H pip3 install -r requirements.txt
He tells me command not found

**Comment by k4m4** [comment]
Can you please re-run the process and **copy/paste every** command and result?

**Comment by psyko59200** [comment]
root@ANDROID:~/Documents/kickthemout-master# sudo -H pip3 install -r requirements.txt
sudo: pip3 : commands not found
root@ANDROID:~/Documents/kickthemout-master# sudo -H pip install -r requirements.txt
Requirement already satisfied: scapy-python3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: python-nmap in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: netifaces in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
root@ANDROID:~/Documents/kickthemout-master# sudo python3 kickthemout.py

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy'

**Comment by k4m4** [comment]
Can you try changing the following code in the `kickthemout.py`:
-`from scapy.config import conf` to `from scapy3k.config import conf`
-

**Comment by k4m4** [comment]
When you run `sudo -H pip install -r requirements.txt` you are installing dependencies for `python2` not `python3`. You should download `pip3` and try reinstalling.

**Comment by psyko59200** [comment]
root@ANDROID:~/Documents/kickthemout-master# sudo -H pip3 install -r requirements.txt
Collecting scapy-python3 (from -r requirements.txt (line 1))
  Downloading scapy-python3-0.23.tar.gz (2.2MB)
    100% |████████████████████████████████| 2.2MB 436kB/s 
Collecting python-nmap (from -r requirements.txt (line 2))
  Downloading python-nmap-0.6.1.tar.gz (41kB)
    100% |████████████████████████████████| 51kB 4.8MB/s 
Collecting netifaces (from -r requirements.txt (line 3))
  Downloading netifaces-0.10.6.tar.gz
Building wheels for collected packages: scapy-python3, python-nmap, netifaces
  Running setup.py bdist_wheel for scapy-python3 ... done
  Stored in directory: /root/.cache/pip/wheels/bc/ac/89/a4b0a177087515cd5e192c6343b402b0909ed2897461a4f857
  Running setup.py bdist_wheel for python-nmap ... done
  Stored in directory: /root/.cache/pip/wheels/d2/20/17/8eb9401fb0fa5ffbd0394c44d9d1c743036896c86029b0a613
  Running setup.py bdist_wheel for netifaces ... done
  Stored in directory: /root/.cache/pip/wheels/28/e1/08/e66a4f207479500a27eae682a4773fa00605f2c5d953257824
Successfully built scapy-python3 python-nmap netifaces
Installing collected packages: scapy-python3, python-nmap, netifaces
Successfully installed netifaces-0.10.6 python-nmap-0.6.1 scapy-python3-0.23
root@ANDROID:~/Documents/kickthemout-master# python3 kickthemout.py 

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy3k'

**Comment by k4m4** [comment]
Change scapy back to `scapy` please.

**Comment by psyko59200** [comment]
Thank you very much it works !!!

**Comment by k4m4** [comment]
No problem, glad it helped.

**Comment by TheC0ndor** [comment]
I had the same problem, just fixed it! In the main lscript folder, go to L shell script, change python kickthemout.py to python3 kickthemout.py and then run ./install.sh and update. Works like charm!

**Comment by AustinUking** [comment]
did someone found the problem?
tells me in the terminal "no module named nmap"
