### ISSUE TITLE
No module named 'Scapy'

### ISSUE THREAD

**Issue by arayaa** [k4m4/kickthemout#281]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

- **OS name & version**: Kali Linux 32 Bit ver. 2018.1
- **Python version**: Python 3.6.5 (default, Apr 12 2018, 22:07:01) | Python 2.7.14+ (default, Apr  2 2018, 04:16:25)
- **Scapy version**: scapy-python3 (0.23) | scapy (2.4.0)
- **Nmap version**: Nmap 7.70
- **Link of [Gist](https://gist.github.com/)**: https://gist.github.com/arayaa/295b4b7149d1f2abb1c2f05bb63e657d

- **Description**: 
```
root@arayaa:~/Desktop/kickthemout-master# pip3 install -r requirements.txt**
_Requirement already satisfied: scapy-python3 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: python-nmap in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: netifaces in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 3))_
r**oot@arayaa:~/Desktop/kickthemout-master# python3 kickthemout.py**

_ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions._

_If you still cannot resolve this error, please submit an issue here:_
	_https://github.com/k4m4/kickthemout/issues_

_Details: No module named 'scapy'_
```

**Comment by k4m4** [comment]
Hi there. Can you try upgrading to the latest version of `pip3` and then re-installing all dependencies? Please post your steps in the process. Thanks.

**Comment by arayaa** [comment]
All of that is the latest ver. 
root@arayaa:~/Desktop/kickthemout-master# pip3 -V
Pip 10.0.0 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
root@arayaa:~/Desktop/kickthemout-master# pip3 install -r requirements.txt
Requirement already satisfied: scapy-python3 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1)) (0.23)
Requirement already satisfied: python-nmap in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2)) (0.6.1)
Requirement already satisfied: netifaces in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 3)) (0.10.6)
root@arayaa:~/Desktop/kickthemout-master# python3 kickthemout.py

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy'

**Comment by k4m4** [comment]
Are you using `sudo`?

**Comment by arayaa** [comment]
yes

**Comment by arayaa** [comment]
I tried with sudo, and it still No module named 'scapy'

**Comment by k4m4** [comment]
Could you share the exact results of `sudo python3 kickthemout.py`? Also, please uninstall all dependencies, re-install them following the exact process in the readme file and share the result of each command here. Thanks!

**Comment by iqbalnur2** [comment]
arayaa
my i help you sir installation?

**Comment by Malik20019** [comment]
i have the same problem.
No module named scapy.
everything is installed correctly then why it is happening?

**Comment by arayaa** [comment]
iqbalnur2 Yes,plz

**Comment by arayaa** [comment]
@Malik20019 yeah, i dont know why, i cant find any reason for that prob

**Comment by arayaa** [comment]
@k4m4 
root@arayaa:~Desktop/kickthemout-master# sudo python3 kickthemout.py

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy'

**Comment by Malik20019** [comment]
All requirements have been satisfied according to README file.
But still the same problem

**Comment by arayaa** [comment]
And they still not give us a way to solve, just repeat: read readme carefully, are u insta it correctly,..  Blabla...

**Comment by k4m4** [comment]
Hey again guys; I am unable to reproduce this. Can anyone send me a walkthrough of their installation process (i.e. all commands run and --> **their responses** <--), please? You're not really giving us anything to work with here... Thanks.

**Comment by arayaa** [comment]
@k4m4 here, https://youtu.be/PDfL6ZIKmRo , plz help me

**Comment by deserboi** [comment]
hey when i put ' sudo apt-get -y install python3-pip' in I get:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-pip
No idea if the last line means anything but nothing changes when putting in the other commands :/

**Comment by k4m4** [comment]
You can try
```
$ sudo apt-get install python3-setuptools
$ sudo easy_install3 pip
```

**Comment by deserboi** [comment]
Thanks for the reply, but it still comes up with some kind of error:
Package python3-setuptools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-setuptools' has no installation candidate
And for the second command it says command not found :/

**Comment by k4m4** [comment]
Have you tried updating your system before running the suggested commands?

**Comment by deserboi** [comment]
Oh yeah, i made a new vm with the updated iso and it worked :P for some reason it doesnt scan all devices on the network though all i get are short ips and 'no vendor' results. Is there any way to fix this?
10.0.2.2		No vendor (_gateway)
10.0.2.3		No vendor (N/A)

**Comment by k4m4** [comment]
Hi again @deserboi. Have you configured your VM network settings correctly? Are you using a bridged connection?

**Comment by deserboi** [comment]
Yeah sorry i plugged in a ethernet cable to the laptop and changed the network settings. It works now, thanks a lot! :))

**Comment by k4m4** [comment]
Glad it worked.
