### ISSUE TITLE
No module named 'scapy.config'

### ISSUE THREAD

**Issue by rjjbog1** [k4m4/kickthemout#283]
I carefully followed installation instructions and all when well until I ran sudo python3 kickthemout.py and got the following error No module named 'scapy.config'.
I'm running the following versions:
OS is Ubuntu 18.04
Python 2.7.14+
Scapy 2.3.3-3
Nmap 7.60-1ubuntu4

**Comment by k4m4** [comment]
Hi there. KickThemOut now works with Python 3+ only, not 2.7.

**Comment by rjjbog1** [comment]
I installed Python 3 and still get the same error, No module named 'scapy.config'

$ python --version Python 3.6.5

Is there anything else I can try?

**Comment by k4m4** [comment]
Did you install all dependencies successfully?

**Comment by rjjbog1** [comment]
Ok, I got it to work. First I had to purge Python 2.7, although I installed Python3 my OS would default to 2.7. After purging 2.7, I no longer got the error No module named scapy.config but did get the error No module named scapy. Second, I found that netifaces was installed as python 2.7 netifaces so I deleted that and installed python3 netifaces. That took care of the problem.

Slick tool.

Thanks.
