### ISSUE TITLE
Error "No module name 'scapy'" When I run kickthemout

### ISSUE THREAD

**Issue by hodonggiang** [k4m4/kickthemout#287]
```
root@kali:~/Desktop/kickthemout# ./kickthemout.py

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy'
```

i read readme.md and i run command but i can't run kickthemout. please help me !!! Thank you

**Comment by k4m4** [comment]
Hi there @hodonggiang. You seem to be using `./kickthemout.py` to run the main script; however, in the README file it states that you should use `sudo python3 kickthemout.py`. Can you try running that please? Thanks.

**Comment by hodonggiang** [comment]
i try using ./kickthemout.py but same error
