### ISSUE TITLE
[Request] python package upload to pypi

### ISSUE THREAD

**Issue by noraj1337** [k4m4/kickthemout#29]
Can you create a python package and upload it to pypi to allow the use of `pip install kickthemout` for more ease of install for new users.

Can see how to do here: https://noraj1337.github.io/Create-python-package-presentation/

**Comment by k4m4** [comment]
We'll take your recommendations into consideration. Thanks!

**Comment by noraj1337** [comment]
You closed this thread but I don't see the `kickthemout` package on pypi.
Is this a ghost **wontfix**?
