### ISSUE TITLE
ERROR: It seems that you are offline. Please check your internet connection.

### ISSUE THREAD

**Issue by Ccor023** [k4m4/kickthemout#291]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**:High Sierra 10.13.4
- **Python version**: 2.7.14
- **Scapy version**:2.4
- **Nmap version**:7.7
- **Link of [Gist](https://gist.github.com/)**"https://gist.github.com/Ccor023/2986056439d2af1ff6deadb9ba444ef2.js"></script>e -->

<br/ >

- **Description**:I have everything downloaded and when I try typing in the command sudo python3 kickthemout.py it says "ERROR: It seems that you are offline. Please check your internet connection." When I ping my connection it is fine and when I try loading something up on a browser it is fine so I do not think it is my internet. Please help!

**Comment by Wafflezzzzz** [comment]
Same here. Help!

**Comment by T0nyX1ang** [comment]
I've read the code here, and I found a possible reason.
```
def checkInternetConnection():
    try:
        urlopen('https://google.com', timeout=3)
        return True
    except URLError as err:
        return False
    except KeyboardInterrupt:
        shutdown()
```
So, if you can't open Google, you will be judged as "offline".
You can change the url here to (maybe) fix that...

**Comment by mortalink** [comment]
Hello guys, same problem here in China as Google is (without a VPN) unreachable due to the government firewall.

I just replaced the:

urlopen('https://google.com', timeout=3)

by:

urlopen('https://www.baidu.com', timeout=3)

**Comment by k4m4** [comment]
Hi there. Yes, this seems to be an issue in some regions where Google is unreachable. Glad that the problem has been resolved.

**Comment by Flori201** [comment]
i have dis problem
