### ISSUE TITLE
No module named scapy.config

### ISSUE THREAD

**Issue by nachobelmonte** [k4m4/kickthemout#302]
$ python --version Python 
Python 2.7.12

$ sudo -H pip3 install -r requirements.txt
Requirement already satisfied: scapy-python3 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (0.24)
Requirement already satisfied: python-nmap in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2)) (0.6.1)
Requirement already satisfied: netifaces in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3)) (0.10.7)

$ sudo python3 kickthemout.py 
ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
        https://github.com/k4m4/kickthemout/issues

Details: No module named scapy.config

how can i resolve this error?

**Comment by lostsystems** [comment]
https://github.com/k4m4/kickthemout/issues/275

This worked for me.

**Comment by lhote2** [comment]
I tried it in kalilinux and it worked, it must be that I need some package to install but I do not know

**Comment by k4m4** [comment]
Hi there @lhote2. Has your issue been solved then?

**Comment by nachobelmonte** [comment]
no, now I'm using this program in kali linux, I do not know what packages I have to install in my kdeneon @k4m4  to work properly

**Comment by MyExcluded** [comment]
cd kickthemout/
pip uninstall -r requirements.txt -y
apt-get update && apt-get full-upgrade -y
apt-get install python3-pip
pip3 install -r requirements.txt
python3 kickthemout.py
[Screencast_05-29-2018_10:56:47 PM.zip](https://github.com/k4m4/kickthemout/files/2051192/Screencast_05-29-2018_10.56.47.PM.zip)
@k4m4

**Comment by k4m4** [comment]
@nachobelmonte Have you installed nmap on your kdeneon? Also, please share the version of python 3 (not 2) you are using and try @MyExcluded's suggested approach. Thanks.

**Comment by nachobelmonte** [comment]
ok, I fixed it, scapy was installed incorrectly thank you so much for the help. Hay algun sitio donde explique como funciona internamente este script? Que es lo que hace que los dispositivos se queden sin acceso a internet? @k4m4

**Comment by ahmedalisha** [comment]
Can you tell me how to install scapy perfectly

**Comment by k4m4** [comment]
Glad you managed to resolve your problem, @nachobelmonte. @ahmedalisha, if you are experiencing a problem, please create a new issue. Thanks!

**Comment by gonzam4** [comment]
solution install scapy sudo python3 kickthemout.py

**Comment by franklinworm** [comment]
Traceback (most recent call last):
  File "kickthemout.py", line 756, in <module>
    defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address, _ = max(iface_routes, key=lambda item:item[1])
ValueError: max() arg is an empty sequence

**Comment by dowardev** [comment]
Do you have correctly installed all the other dependencies?

**Comment by liltato69** [comment]
python3 kickthemout.py    CRITICAL: Can't open /proc/net/dev !                    CRITICAL: Can't open /proc/net/route !
CRITICAL: Can't open /proc/net/dev !
Traceback (most recent call last):
  File "/root/kickthemout/kickthemout.py", line 756, in <module>
    defaultInterface = getDefaultInterface()
  File "/root/kickthemout/kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address, _ = max(iface_routes, key=lambda item:item[1])
ValueError: max() arg is an empty sequence
