### ISSUE TITLE
Requirements have not been satisfied properly. 

### ISSUE THREAD

**Issue by Rahul13936** [k4m4/kickthemout#303]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**:

**Comment by Rahul13936** [comment]
os name & version = kali linux 2018.2
python version = 2.7.14+
scapy version = 2.2.0
nmap version = 7.70

Description : everything is setted up with requirements but still its not working 
showing the requirement error

**Comment by k4m4** [comment]
Hi there. Have you followed the latest installation guide, as specified in the readme file? KickThemOut now works with python3 and not python2. Thanks.

**Comment by Rahul13936** [comment]
Run it as python3 in command instead of just writing python in command it
will work for sure. Cause it's working for me now
