### ISSUE TITLE
Attack unsuccessful

### ISSUE THREAD

**Issue by smtkymt** [k4m4/kickthemout#307]
![asf](https://user-images.githubusercontent.com/40278866/41439058-0088bff8-7032-11e8-990e-db56fdd22fd5.png)

KickThemOut is detecting my targets but (found everytime 2 same targets!) and the attack is unsuccessful just waiting all time!

**Comment by k4m4** [comment]
Hi there @smtkymt. Based on the image you have sent, it seems that everything is running as expected. What do you mean by saying that "the attack is unsuccessful"? Thanks!
