### ISSUE TITLE
does the software still work

### ISSUE THREAD

**Issue by Blisteur** [k4m4/kickthemout#311]
Hello. does the software still work? because at me no.
Thank you for your reply

**Comment by MrdotSpock** [comment]
Hello,

Can you please specify what exactly is not working?

Regards

**Comment by Blisteur** [comment]
Thank you for your answer, the device that I try to disconnect does not disconnect

**Comment by NickWho** [comment]
@Blisteur Hi,
Actually it does still work. Are you using a VM for using KickThemOut.py or a main Computer with Linux installed ? 
Because earlier i had the Problem too, that i couldn't kick people out of my Network. But then i just find out, that i could fix the Issue by installing Linux on my Notebook.

**Comment by Blisteur** [comment]
it is installed on a dedicated laptop

**Comment by MrdotSpock** [comment]
If I understand it correctly you want to disconnect device which is running this script. Is that right?

**Comment by Blisteur** [comment]
no I try to disconnect my phone from the laptop

**Comment by Blisteur** [comment]
Yes I see it but when I try to disconnect it it turns in the void

**Comment by k4m4** [comment]
Hi there @Blisteur. This issue seems pretty vague to me. Could you please clarify why you have come to the conclusion that KickThemOut is not working? In an issue, you are meant to give us something that we can work with, not just draw an unclear conclusion. Thanks.

**Comment by Blisteur** [comment]
Hello, I came to this conclusion because after testing this software it can not disconnect a device from the network, it is blocked at the time of the attack and runs in a vacuum.
Thank you for your reply.
sorry for my poor English.

**Comment by k4m4** [comment]
Hi again. Could you please elaborate what you mean by "it is blocked at the time of the attack" and "runs in a vacuum"? Thanks again.

**Comment by Blisteur** [comment]
the attack is blocked at "Spoofing started ...
"and does not change even after 20 minutes.

**Comment by k4m4** [comment]
Well, that's precisely what should happen. Once the attack begins, the text "Spoofing started" indicates that the ARP spoofing packets are now being sent out to the victim (meaning that if you open up Wireshark or any other packet monitoring software, you should be able to see the packets being broadcasted). When you select ^C, then the attack stops and the target is 're-ARPed'. I yet cannot see why you believe that KickThemOut is "blocked at the time of the attack" and "runs in a vacuum". Thanks.

**Comment by Blisteur** [comment]
I think it is stuck at the time of the attack because watching with wireshark I do not see anything and the phone does not disconnect,
"runs in the void" is a French expression meaning that it charges indefinitely.
sorry for my approximate English.

**Comment by k4m4** [comment]
Could you please share a screenshot or screen-recording of Wireshark after the attack has began? No worries for the language.

**Comment by Blisteur** [comment]
there is a problem, I do not see any device.

https://youtu.be/fXHGF00sEBE

https://youtu.be/WyDYHdiho44

**Comment by k4m4** [comment]
Can you please share a video showing Wireshark packets once KickTheOut has started running? These two videos don't show the traffic while the attack is actually in progress. Thanks again.

**Comment by Blisteur** [comment]
I just succeeded, I just restart my router, by chance you know why I receive posts in wireshark because I had never had before trying KickThemOut

and thank you again.


https://youtu.be/nEUZschxVDM

**Comment by k4m4** [comment]
Glad it worked!

**Comment by MrNerDD** [comment]
me also getting this issue . please somebody help how it can be fixed

**Comment by MrNerDD** [comment]
> I just succeeded, I just restart my router, by chance you know why I receive posts in wireshark because I had never had before trying KickThemOut
> 
> and thank you again.
> 
> https://youtu.be/nEUZschxVDM

how did you fixed this issue ?i am facing this same issue
