### ISSUE TITLE
ERROR: It seems that you are offline. Please check your internet connection.

### ISSUE THREAD

**Issue by Blackwolf499** [k4m4/kickthemout#315]
I've been using kickthemout for some time. It was working before hand up until I tried enabling monitor mode which apparently I can no longer do. Even though I use to be able to do it. I've searched up this error and tried every solution but i couldn't find anything of it.

I have re-installed it and made sure the requirements were fulfilled.
I have also tried changing the https://google.com to a different website. Still no success,

I'm running kali on a MacBook Pro 2013.
Any Ideas for what I should do?

Thanks In advance.

**Comment by k4m4** [comment]
Hi there @Blackwolf499. Thank you for taking the time to open this issue. Are you getting some error message you can share with us, or does the ARP-spoofing attack not work even though you see the `Spoofing started` message?

**Comment by Blackwolf499** [comment]
Hi km4m, sorry for the late reply,
I do not see 'Spoofing Started'

I start the process by doing: cd kickthemout/
sudo python3 kickthemout.py

and I'm given the error message: ERROR: It seems that you are offline. Please check your internet connection.

Any help will be great.
Thanks In advance,

**Comment by k4m4** [comment]
Hi again, have you connected your Kali VM to the internet? Are you using a bridged connection? Thanks again.

**Comment by Blackwolf499** [comment]
Hey k4m4, I'm not using a virtual machine as I've single booted kali onto my mac.

**Comment by k4m4** [comment]
Oh, okay. So I assume that you have a working internet connection. Can you verify that you are able to ping google?

**Comment by k4m4** [comment]
Hi there @Blackwolf499. Please forgive my delayed response. Are you still experiencing this issue? Thanks for your patience.

**Comment by asturksever** [comment]
@k4m4 I m also facing with the same problem as @Blackwolf499. I can ping google.com but i got  "ERROR: It seems that you are offline. Please check your internet connection." error.

**Comment by Blackwolf499** [comment]
I managed to fix it.
Alright so I played around and deleted an entire line that actually checks for the connection which i did before hand and didn't work although, this time it did work.
@k4m4 @asturksever

**Comment by Fomazou** [comment]
I have a same problem and try to fix it. when i make DHCP network configuration, all thing is right. but with static configuration i have ERROR: It seems that you are offline. Please check your internet connection.
how do i do in Local Area Network with static configuration!!

**Comment by LulzsecHackz** [comment]
I had the same issue, i had this type of issue with other tools. The check for internet lines are not working properly. You need to delete them, do.   nano kickthemout.py    hold the CMD and press K to search lines... enter      checkinternetcon      now delete every file that contains this word, delete the definition and the action which are in the middle of the script... run the script for troubleshooting(to see if gives any error) if yes then u may deleted too much or to less, or the wrong line...

**Comment by k4m4** [comment]
Hey guys. This should have been resolved in pull req. #341. If you have access to GitHub, then you should be able to pass the _checkInternetConnection_ check. Thanks!
