### ISSUE TITLE
Details: 'errors' is an invalid keyword argument for this function "

### ISSUE THREAD

**Issue by Aspiracy** [k4m4/kickthemout#317]
Checklist for submitting an issue to KickThemOut:
[yes] I have carefully read the README file and haven't managed to resolve my issue.
[yes] I have searched the issues of this repo and believe that this is not a duplicate.
[yes] I am running the latest version of KickThemOut.
OS name & version:
Python version:
*Scapy version
Nmap version:
Link of Gist:

Description: so originally, after following all steps in the read me and running "python kickthemout.py" i had an error saying "no modules named nmap" now i solved that just now by running "sudo pip -r requirements.txt" or something along those lines. now after that im getting this error:
" ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
https://github.com/k4m4/kickthemout/issues

Details: 'errors' is an invalid keyword argument for this function "

now im completely confused. has anyone resolved this issue already? any help?

(COPIED THIS FROM ORGIN4 or somethin BECAUSE I DID THAT TOO)

**Comment by k4m4** [comment]
Hi there @Aspiracy. Could you please share the information that is included in the issue template? We don't have anything to work with at the moment. Thanks!

**Comment by Aspiracy** [comment]
i fixed the issue, its okay now Nikolaos,
\

PS: I love this expoilt so much!!! trolling people in starbucks!

**Comment by k4m4** [comment]
Glad to hear that it works, @Aspiracy. Thanks! (P.S. make sure to stay on the legal side of things)
