### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Aspiracy** [k4m4/kickthemout#319]
sudo python3.7 kickthemout.py 

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'nmap'

I READ ALL INSTRUCTIONS
DID ALL WHAT IT SAID 
LATEST VERSION PYTHON 3.7!

WHAT IS UP? it been broken since v2.0 UPDATE DUDE!

**Comment by k4m4** [comment]
Hi there. It seems like you haven't downloaded `nmap`. What OS are you running? On a Linux machine you should run `apt install nmap` or `brew install nmap` on a macOS machine. Thanks!

**Comment by Aspiracy** [comment]
EVerything good now!

**Comment by k4m4** [comment]
Glad to hear that, thanks!
