### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getts'

### ISSUE THREAD

**Issue by tinmar33** [k4m4/kickthemout#32]
Hello,

I have this error when i launch the script on OS X Sierra, any idea ?

`AttributeError: 'NoneType' object has no attribute 'getts'`

**Comment by k4m4** [comment]
Check out [#8](https://github.com/k4m4/kickthemout/issues/8). Let me know if you manage to resolve the issue.

**Comment by k4m4** [comment]
This is most probably because of misconfiguration. Try following the installation process for Mac OS X in the [README.rst](https://github.com/k4m4/kickthemout/blob/master/README.rst#mac-os-x-installation) file.

**Comment by tinmar33** [comment]
I have reinstalled scapy libdnet and python and it finally works, thanks ;)

**Comment by k4m4** [comment]
Good to hear! :)
