### ISSUE TITLE
no module named 'scapy' & requirements have not been satisfied properly.....

### ISSUE THREAD

**Issue by xxzBreezyyxx** [k4m4/kickthemout#322]
## Checklist for submitting an issue to `KickThemOut`:

- [check] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [check] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [check] I am running the latest version of KickThemOut.

 

- **OS name & version**: Linux version 4.15.0-kali2-amd64 (devel@kali.org) (gcc version 7.3.0 (Debian 7.3.0-11)) #1 SMP Debian 4.15.11-1kali1 (2018-03-21)
- **Python version**: 2.7.14 (i have also 10.6.0)
- **Scapy version**: I don't know yet
- **Nmap version**: 7.70
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**: when I try: 'Sudo python3 kickthemout.py', kali linux says after it: 'ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy''

P.S.: ‘sudo apt-get install python3-pip
and
sudo -H pip3 install -r requirements.txt‘ also didn’t worked.....

**Comment by MeSoHorny13** [comment]
I tried to installed using the lazy script and manually also didn't work `

NO module named 'scapy'

**Comment by xxzBreezyyxx** [comment]
Yes, I already tried everything what was told in the other issues, but no one helped me, hope someone will help me.....

**Comment by xxzBreezyyxx** [comment]
No, unfortunately that isn’t working for me, I tried everything I think, hope for some help

**Comment by mohaMesto** [comment]
please help me too

**Comment by mohaMesto** [comment]
the same

**Comment by xxzBreezyyxx** [comment]
TeslaSSTec yes im Very interested in that if it will make it work!

**Comment by k4m4** [comment]
Hi there @xxzBreezyyxx. Can you walk me through the steps that you've taken to download scapy?

**Comment by corrosive8** [comment]
i am getting the same error.
i have already checked the version on python3 (everything seems fine)
the installation of "requirements.txt" goes smooth, but when i run "sudo python3 kickthemout.py " i am always getting an error.
did someone find a solution? 
@k4m4  thanx in advance

**Comment by xxzBreezyyxx** [comment]
I have walked trough everything

Op dinsdag 2 oktober 2018 heeft corrosive8 <notifications@github.com> het
volgende geschreven:

**Comment by SevenChords** [comment]
getting the same error on macos 10.14, tried everything, still the same error with scapy

**Comment by k4m4** [comment]
Hey guys. Please try to reinstall KickThemOut and all its dependencies; I have upgraded Scapy to the latest Kamene build. Let me know if the new release solves your issue. Thanks!

**Comment by xxzBreezyyxx** [comment]
Doesn’t work

Op woensdag 7 november 2018 heeft Nikolaos Kamarinakis <
notifications@github.com> het volgende geschreven:

**Comment by k4m4** [comment]
@xxzBreezyyxx, please open a new issue if you are still experiencing this problem. Thanks!
