### ISSUE TITLE
ValueError : max() arg is an empty sequence 

### ISSUE THREAD

**Issue by z1ka** [k4m4/kickthemout#324]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

<br/ >

- **Description**: 

root@kali:~/kickthemout# python3 kickthemout.py
Traceback (most recent call last):                                   File "kickthemout.py", line 754, in <module>
    defaultInterface = getDefaultInterface()                         File "kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: max() arg is an empty sequence                        

can't find the fix here i installed it right and followed the readme file and still no luck , i am using kali nethunter

**Comment by k4m4** [comment]
Hey there @z1ka. This problem should be solved in the latest release. Thanks!

**Comment by gustimanunggal** [comment]
No still not fixed, same me!

**Comment by k4m4** [comment]
@gustimanunggal Please create a new issue with all the relevant information. Thanks!
