### ISSUE TITLE
Wrong type for [hosts]

### ISSUE THREAD

**Issue by denningsrogue** [k4m4/kickthemout#327]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**:  Mac OS High Sierra 10.13.6
- **Python version**:  3.7.0
- **Scapy version**: scapy-python3 0.25
- **Nmap version**:  Nmap version 7.70
- **Link of [Gist](https://gist.github.com/)**: <"https://gist.github.com/denningsrogue/f26750c37dbad96a231840753493d5a4.js"

<br/ >

- **Description**: 

When I run the script here is the result:

ERROR: Gateway IP could not be obtained. Please enter IP manually.

kickthemout> Enter Gateway IP (e.g. 192.168.1.1): 10.0.1.1

ERROR: Default Interface MAC Address could not be obtained. Please enter MAC manually.

kickthemout> Enter MAC Address (MM:MM:MM:SS:SS:SS): xx:xx:xx:xx:xx:xx
Scanning your network, hang on...

ERROR: Network scanning failed. Please check your requirements configuration.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: Wrong type for [hosts], should be a string [was <class 'NoneType'>]

**Comment by k4m4** [comment]
Hi there. Apologies for the delayed response. Are you still experiencing this issue? Thanks!

**Comment by iWrek** [comment]
Hi, I am receiving this issue as well.

**Comment by k4m4** [comment]
Hey there @denningsrogue & @iWrek. Please try to reinstall KickThemOut and all its dependencies; I have upgraded Scapy to the latest Kamene build. Let me know if the new release solves your issue. Thanks!

**Comment by k4m4** [comment]
Good to hear that!
