### ISSUE TITLE
no module named scapy

### ISSUE THREAD

**Issue by sandeshchaudhary123456789** [k4m4/kickthemout#333]
## Checklist for submitting an issue to `KickThemOut`:

- [ ] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [ ] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [ ] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**:

**Comment by JJSCASTRO** [comment]
I fixed it by:
1. Uninstalling Python 2
2. Uninstalling Python 3
3. Installing Python 3
4. In some cases brew will ask you to link it so do that
5. `cd kickthemout/`
6. `sudo -H pip3 install -r requirements.txt`
Done.

**Comment by k4m4** [comment]
Hi there @sandeshchaudhary123456789. Are you still experiencing this issue?
