### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by djkahled** [k4m4/kickthemout#334]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: Python 2 and 3.6.5-3
- **Scapy version**: 2.40-2
- **Nmap version**: 7.7
- **I dont know how to make a gist link :/ 

- **Description**: After running python3 kickthemout.py it goes straight into scanning networks (so i dont get the usual interface that asks me what to do). And after that it returns me this:

root@kali:~/Desktop/kickthemout# sudo python3 kickthemout.py
Traceback (most recent call last):
  File "kickthemout.py", line 788, in <module>
    main()
  File "kickthemout.py", line 623, in main
    heading()
  File "kickthemout.py", line 58, in heading
    '\n' + 'Version: {}2.0{} \n'.format(YELLOW, END).center(86))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2588' in position 88: ordinal not in range(128)
root@kali:~/Desktop/kickthemout#

**Comment by borekon** [comment]
It's a enconding displaying... the header colors......
Just add a # in the [line 626](https://github.com/k4m4/kickthemout/blob/861aea2102369b2e8c5d86db39d6a5a4d130d02f/kickthemout.py#L626) to make the program not calling the banner and info option
