### ISSUE TITLE
ValueError: too many values to unpack (expected 5)

### ISSUE THREAD

**Issue by Cyber-hunter** [k4m4/kickthemout#335]
Traceback (most recent call last):
  File "kickthemout.py", line 754, in <module>
    defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: too many values to unpack (expected 5)

**OS : Deepin v15.7
Python : 3.6.5
pip : 9.0.1
python3-nmap : 0.6.1
python3-scapy : 0.23
python3-netifaces : 0.10.4**

**Comment by paranoid73** [comment]
I use Arch linux , i removed packages python2-scapy , python2-netifaces and python2-nmap and uninstall Kickthemout from AUR, next git clone from here and sudo -H pip3 install -r requirements.txt

**Comment by Cyber-hunter** [comment]
Unfortunately yes .

**Comment by k4m4** [comment]
Can you try running pull req #294. Let me know if that works for you. Thanks!

**Comment by Cyber-hunter** [comment]
thank it's work for me .
by adding 
`try:
        network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
    except:
        network, netmask, _, interface, address, _ = max(iface_routes, key=lambda item:item[1])`

**Comment by k4m4** [comment]
Glad to hear that!
