### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by syauqi1988** [k4m4/kickthemout#339]
## Checklist for submitting an issue to `KickThemOut`:

- [x ] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x ] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x ] I am running the latest version of KickThemOut.

 

- **OS name & version**: android termux
- **Python version**: python3
- **Scapy version**: 
- **Nmap version**: 7.7
- **Link of [Gist](https://gist.github.com/)**: 

$ tsudo python3 kickthemout.py

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
        https://github.com/k4m4/kickthemout/issues

Details: [Errno 13] Permission denied: '/data/data/com.termux/files/usr/bin/sh'
$

can someone help me with this issue. my. Im usin rooted samsung galaxy note 5 with permissive selinux.  <br/ >

- **Description**:  permission denied

**Comment by Saloooh8181** [comment]
I have the same problem
