### ISSUE TITLE
PIP package scapy-python3 error

### ISSUE THREAD

**Issue by Danikrlop47** [k4m4/kickthemout#345]
PIP package scapy-python3 used to provide scapy3k, which was a fork from scapy implementing python3 compatibility since 2016. This package was included in some of the Linux distros under name of python3-scapy. Starting from scapy version 2.4 (released in March, 2018) mainstream scapy supports python3. To reduce any confusion scapy3k was renamed to kamene.
You should use either pip package kamene for scapy3k (see http://github.com/phaethon/kamene for differences in use) or mainstream scapy (pip package scapy, http://github.com/secdev/scapy).

please help im on a macbook pro

**Comment by MrNerDD** [comment]
please tell me if you have fixed this issue

**Comment by darantares** [comment]
Do **pip install scapy**

You don't have to install Scapy 3 for python anymore, since Python 3 supports scapy.

**Comment by k4m4** [comment]
Hey guys. Please try to reinstall KickThemOut and all its dependencies; I have upgraded `Scapy` to the latest `Kamene` build which should resolve this dependency error. If your problem still occurs, please re-open the issue. Thanks!

**Comment by xstorm25** [comment]
can you please give us more informations about upgrade scapy to kamene.

**Comment by xstorm25** [comment]
> Do **pip install scapy**
> 
> You don't have to install Scapy 3 for python anymore, since Python 3 supports scapy.

how we can fix it
