### ISSUE TITLE
Please I need help :)

### ISSUE THREAD

**Issue by kenITpro** [k4m4/kickthemout#347]
## Checklist for submitting an issue to `KickThemOut`:

- [ ] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [ ] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [ ] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

sudo python3 kickthemout.py
[sudo] password for xziim: 
Sorry, try again.
[sudo] password for xziim: 

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy.config'

**Comment by k4m4** [comment]
Hey there @kenITpro. Please try to reinstall KickThemOut and all its dependencies; I have upgraded Scapy to the latest Kamene build which should resolve this dependency error. If your problem still occurs, please re-open the issue. Thanks!
