### ISSUE TITLE
Those anyone here know how to install kickthemout in ubuntu 16.04?

### ISSUE THREAD

**Issue by DarkInternet** [k4m4/kickthemout#348]
I try to install kickthemout in ubuntu 16.04 using debian guide and i install all requirements 
scapy-python3
python-nmap
netifaces

but i face error 

> kaganovich@xKaganovich:~/kickthemout$ sudo python3 kickthemout.py

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: No module named 'scapy.config'

**Comment by fam4r** [comment]
Same error in ArchLinux using AUR package: https://aur.archlinux.org/packages/kickthemout-git

**Comment by k4m4** [comment]
Hey guys. Please try to reinstall KickThemOut and all its dependencies; I have upgraded `Scapy` to the latest `Kamene` build which should resolve this dependency error. Please re-open the issue if the problem persists. Thanks!
