### ISSUE TITLE
Details: No module named 'scapy.config'

### ISSUE THREAD

**Issue by winw0r1d** [k4m4/kickthemout#349]
How do I figure that out? Thanks for the answer

**Comment by winw0r1d** [comment]
Linux kali 4.12.0-kali1-amd64 #1 SMP Debian 4.12.6-1kali6 (2017-08-30) x86_64 GNU/Linux

**Comment by denningsrogue** [comment]
Same issue here on macOS Mojave 10.14

**Comment by denningsrogue** [comment]
Running sudo -H python3 -m pip install -r requirements.txt shows all the requirements satisfied.

**Comment by denningsrogue** [comment]
Here is the output:
Requirement already satisfied: scapy-python3 in /Users/me/.pyenv/versions/3.7.0/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (0.26)
Requirement already satisfied: python-nmap in /Users/me/.pyenv/versions/3.7.0/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (0.6.1)
Requirement already satisfied: netifaces in /Users/me/.pyenv/versions/3.7.0/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.10.7)

**Comment by BlueArduino20** [comment]
Try:
``sudo apt-get install python3-scapy``

**Comment by SevenChords** [comment]
the sudo apt-get install python3-scapy gives back an error that the command apt-get cannot be found, running latest version of macos mojave

**Comment by BlueArduino20** [comment]
Apt-get is for linux @SevenChords

**Comment by SevenChords** [comment]
yeah, but denningsrogue and i are both on mac, any idea how we can get our problem fixed?

**Comment by BlueArduino20** [comment]
``brew install libdnet``

**Comment by SevenChords** [comment]
libdnet is already installed, what i think the problem is that the scapy port for python3 that is used in kickthemout is deprecated as stated by another error i got which says that kamene or mainstream scapy should be used

**Comment by k4m4** [comment]
Hey guys. Please try to reinstall KickThemOut and all its dependencies; I have upgraded `Scapy` to the latest `Kamene` build which should resolve this dependency error. Please re-open the issue if the problem persists. Thanks!
