### ISSUE TITLE
python3 kickthemout.py - ERRORS

### ISSUE THREAD

**Issue by hipstersabotage** [k4m4/kickthemout#350]
Traceback (most recent call last):
  File "kickthemout.py", line 754, in <module>
    defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: too many values to unpack (expected 5)

can you help me ?

Parrot OS.

**Comment by k4m4** [comment]
Hey there @hipstersabotage. Please try to reinstall KickThemOut and all its dependencies; I have upgraded `Scapy` to the latest `Kamene` build which should resolve this value error. Please re-open the issue if the problem persists. Thanks!
