### ISSUE TITLE
sudo python3 kickthemout.py

### ISSUE THREAD

**Issue by selbyh1** [k4m4/kickthemout#354]
Os= Mac 2014 OS X
Python= 3
Scapy=0.26
Nmap=6.1

 When I run - sudo python3 kickthemout.py it tells me

Traceback (most recent call last):
  File "kickthemout.py", line 754, in <module>
    defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: too many values to unpack (expected 5)

**Comment by k4m4** [comment]
Hey there @selbyh1. Please try to reinstall KickThemOut and all its dependencies; I have upgraded `Scapy` to the latest `Kamene` build which should resolve this value error. Please re-open the issue if the problem persists. Thanks!
