### ISSUE TITLE
error while installing on macOS High Siri

### ISSUE THREAD

**Issue by ahmarkaka** [k4m4/kickthemout#356]
## Checklist for submitting an issue to `KickThemOut`:

- [ ] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [ ] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [ ] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Kamene version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Ahmars-MacBook-Pro:kickthemout ahmar$ sudo -H pip3 install -r requirements.txt
sudo: pip3: command not found**:

**Comment by k4m4** [comment]
Hi there. You haven't downloaded [`pip`](https://pip.pypa.io/en/stable/installing/), which is required for downloading Python packages.

**Comment by k4m4** [comment]
Follow the link on my pervious comment to find an installation guide. In the meantime, I am closing this issue since it is irrelevant to KickThemOut. Let me know if you need any help. Thanks.

**Comment by ahmarkaka** [comment]
Yes i have downloaded from the link you given in the homebrew..

**Comment by ahmarkaka** [comment]
Hi there thanks for your reply..
Can you give ma link from where to download the pip3...
Becausei m a mac user and don't know more  about python

**Comment by ahmarkaka** [comment]
I have downloaded the pip3 but it still showing  that sudo : pip3 : command
not found

**Comment by k4m4** [comment]
@ahmarkaka If you see `sudo : pip3 : command not found`, then you haven't installed pip3 correctly. Try following [this link](https://pip.pypa.io/en/stable/installing/).
