### ISSUE TITLE
Mac OS El Capitain not working

### ISSUE THREAD

**Issue by FrostyModz** [k4m4/kickthemout#36]
I installed all the requirements but still shows this

ERROR: Requirements have not been properly satisfied. Please try running:
	$ sudo pip install -r requirements.txt

If you still get the same error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

**Comment by k4m4** [comment]
Check out the following issues: [#13](https://github.com/k4m4/kickthemout/issues/13), [#7](https://github.com/k4m4/kickthemout/issues/7) & [#10](https://github.com/k4m4/kickthemout/issues/10). Please let me know if this resolves your issue. Thanks.

**Comment by FrostyModz** [comment]
i can run it! i selected the first option and when to the number where my phone IP was and then 1 typed the number before IP [1] 192.168.0.12 and then i still had internet on my phone. im on a mac book pro. do i need an external Wifi card? one of those USb things?

**Comment by k4m4** [comment]
Hi there. Does this issue still occur? @FrostyModz

**Comment by FrostyModz** [comment]
Yes. I can run but the devices stull have internet. if im pinging 8.8.8.8 on my windows laptop it stops pinging but i still have internet connection! I can even go to google and any other website.

**Comment by k4m4** [comment]
That doesn't make much sense @FrostyModz. 8.8.8.8 is google.com, so if you receive no response, then you shouldn't be able to browse google.com.

**Comment by FrostyModz** [comment]
Still having this issue. Yes

**Comment by FrostyModz** [comment]
I don't know if you believe me. But I can make a video for proof
