### ISSUE TITLE
no module named kamena

### ISSUE THREAD

**Issue by freakie123** [k4m4/kickthemout#360]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [ ] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [ ] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Kamene version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**:

**Comment by selbyh1** [comment]
whats your OS?

**Comment by k4m4** [comment]
Closing due to insufficient information provided. Feel free to open a new issue with all appropriate information. Thanks.
