### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u2588' in position 88: ordinal not in range(128)

### ISSUE THREAD

**Issue by NaimJones16** [k4m4/kickthemout#362]
## Checklist for submitting an issue to `KickThemOut`:

- [X] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [X] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [X] I am running the latest version of KickThemOut.

 

- **OS name & version**:  Linux kali 4.14.71-kali-v7+
- **Python version**:   Python 3.6
- **Kamene version**:  Kamene was recently installed and updated
- **Nmap version**:  Nmap version 7
- **Link of [Gist](https://gist.github.com/)**: 

When typing in the code sudo python3 kickthemout.py   

It will load for a long time then states that the gateway ip could not be obtained and to enter manually, when i do i get this error.

Traceback (most recent call last):
  File "kickthemout.py", line 788, in <module>
    main()
  File "kickthemout.py", line 623, in main
    heading()
  File "kickthemout.py", line 58, in heading
    '\n' + 'Version: {}2.0{} \n'.format(YELLOW, END).center(86))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2588' in position 88: ordinal not in range(128)

Please Help i've been working to figure this out for about two days now.

**Comment by borekon** [comment]
It's a enconding displaying... the header colors......
Just add a # in the [line 626](https://github.com/k4m4/kickthemout/blob/861aea2102369b2e8c5d86db39d6a5a4d130d02f/kickthemout.py#L626) to make the program not calling the banner and info option

**Comment by k4m4** [comment]
Closing since this is a duplicate issue. Thanks!
