### ISSUE TITLE
kickthemout does not kick the targets on kali.

### ISSUE THREAD

**Issue by sindikto** [k4m4/kickthemout#372]
![captura de pantalla de 2019-01-12 22-17-14](https://user-images.githubusercontent.com/45392727/51089520-ee197d00-176e-11e9-9c83-62d081e7f540.png)

## Checklist for submitting an issue to `KickThemOut`:

- [X] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [X] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [X] I am running the latest version of KickThemOut.

 
- **Kali ver. 2019.1**: 
- **python version  3.6.8**: 
- **Linux KATANA 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux**: 
- **nmap version 7.70**: 
- **https://gist.github.com/sindikto**: 
<br/ >
- **kickthemout does not kick the targets on kali.
![captura de pantalla de 2019-01-13 15-24-02](https://user-images.githubusercontent.com/45392727/51088112-26639000-175c-11e9-9917-395b71a2a9e9.png)
**:

**Comment by sindikto** [comment]
Now kickthemout no start  
![captura de pantalla de 2019-01-21 12-47-44](https://user-images.githubusercontent.com/45392727/51472851-f67b4480-1d7a-11e9-924c-1385832a2511.png)
what can I do?

**Comment by kel12345678** [comment]
hello for fix this error sudo apt-get install python3-pip(in new terminal)and reinstall the script and requirements;)

**Comment by k4m4** [comment]
Hi there. Based on your screenshot, it seems that you are trying to run KickThemOut with Python 2.7. Please follow the python3 installation guide located in the readme file and make sure that you are using Python 3 instead of Python 2. Thanks!

**Comment by tippytactics** [comment]
I fixed it by running it with this command "sudo python3 kickthemout.py". I first tried like you too but got the same error then with this command it ran perfectly
