### ISSUE TITLE
ubuntu install?

### ISSUE THREAD

**Issue by seba8336** [k4m4/kickthemout#374]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Kamene version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**:

**Comment by seba8336** [comment]
i know this is kind of a "noob" question but how to install in ubuntu (18.10) i searched the web but couldnt find any way to install it.

(i tried the debian installation but it did not work)

**Comment by k4m4** [comment]
Hi there. The installation guide can be found in the readme file of the repo. If you are having specific problems while running the installation commands, please create a new issue outlining the error that you are encountering. Thanks!
