### ISSUE TITLE
Requirement already satisfied 'kamene'

### ISSUE THREAD

**Issue by arshit09** [k4m4/kickthemout#376]
I had installed all the requirements successfully. But while running 'kickthemout.py' by './kickthemout.py' - I'm getting error : 

Details: No module named 'kamene'

To resolve that - when I entered 'pip install kamene' to install "kamene" - I'm getting this -
"Requirement already satisfied"

**Comment by rickwierenga** [comment]
try `python3 -m pip install kamene`

**Comment by k4m4** [comment]
Hi there @arshit09. Please follow the installation guide, located in the readme file of this repo. If you have any further problems, please open a new issue. Thanks!
