### ISSUE TITLE
Scapy Not Working, Read all other issues

### ISSUE THREAD

**Issue by iamianthomas** [k4m4/kickthemout#38]
@k4m4
@xdavidhu
I am on Linux Mint. 18.1, Serena. I get the same message. I try uninstalling Scapy, but it says it is not installed. This is what it says:

# sudo pip install scapy
Collecting scapy
  Using cached scapy-2.3.3.tgz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-at_svc1r/scapy/setup.py", line 36
        os.chmod(fname, 0755)
                           ^
    SyntaxError: invalid token
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-at_svc1r/scapy/

Any help is appreciated. Again, I have tried to fix it and uuninstall it and so on, Thanks.

**Comment by k4m4** [comment]
Look at the solution to [Issue #37](https://github.com/k4m4/kickthemout/issues/37). Let me know if this resolves your issue. Thanks!

**Comment by iamianthomas** [comment]
Yeah I fixed it...
