### ISSUE TITLE
requirements not satisfied 

### ISSUE THREAD

**Issue by Detora** [k4m4/kickthemout#39]
After I pulled the code with 'git clone https://github.com/k4m4/kickthemout.git' and downloaded 'scapy' with pip ('pip install -r requirements.txt') I still get the following message:

$ pip install -r requirements.txt
Requirement already satisfied: scapy in c:\python27\lib\site-packages (from -r requirements.txt (line 1))

$ python kickthemout.py

ERROR: Requirements have not been properly satisfied. Please try running:
$ sudo pip install -r requirements.txt

If you still get the same error, please submit an issue here:
https://github.com/k4m4/kickthemout/issues
i tried to unistall scpy but i got this:
sudo pip uninstall scapy
Not uninstalling scapy at /usr/lib/python2.7/dist-packages, owned by OS

**Comment by Detora** [comment]
tried to uninstall it so i could reinstall it

**Comment by k4m4** [comment]
Try running `sudo pip uninstall scapy` and then `sudo pip install scapy`. There shouldn't be any issues with this in Kali. Please let me know if your issue gets resolved. Thanks.

**Comment by k4m4** [comment]
The solution to this issue can be found here: [Issue #37](https://github.com/k4m4/kickthemout/issues/37). Thanks!
