### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by cahyosh** [k4m4/kickthemout#393]
```
Traceback (most recent call last):
  File "kickthemout.py", line 753, in <module>
    defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
ValueError: max() arg is an empty sequence
```

**Comment by PLEASEFORGETME2** [comment]
I have the same problem. On my computer it works, but when I try it on my phone ( app : UserLAnd, kali linux machine ) I get this error.
I installed all requirements without problems.
If there some informations missing, tell me. 
Thanks

**Comment by k4m4** [comment]
Hi there @PLEASEFORGETME2. Please create a new issue. Thanks.

**Comment by k4m4** [comment]
Closing this due to the author's inactivity.
