### ISSUE TITLE
Scanning your network hang on - unable to provide MAC Address

### ISSUE THREAD

**Issue by barthol0** [k4m4/kickthemout#399]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: Manjaro Linux x86_64, kernel 5.0.15-1-MANJARO 
- **Python version**: 3.7.3
- **Kamene version**: 3.0.0
- **Nmap version**: 7.70
- **Link of [Gist](https://gist.github.com/barthol0/d39ec40f358616d2354f59cc572ffa7b)** 

<br/ >

- **Description**: 
Hi,
kickthemout hangs on 'Scanning your network, hang on...'
```
➜  kickthemout git:(master) sudo python kickthemout.py 
SCanning your network, hang on...
ERROR: Default Gateway MAC Address could not be obtained. Please enter MAC manually.

Enter your gateway's MAC Address (MM:MM:MM:SS:SS:SS): ScAnning your^Canning your network, hang On...

Thanks for dropping by.
Catch ya later!
```
I had to kill it with ctrl+c. I was unable to provide MAC address. 
It looks like the issue is quite common. I'm more than happy to help.

Cheers,
Bart

**Comment by k4m4** [comment]
Hi there @barthol0. Thank you for bringing this up. Indeed, it is a bug that needs to be resolved.

**Comment by yarin177** [comment]
+1 It worked for me the first time I tried since then i'm getting this error as well.

**Comment by MohcenCH** [comment]
same here

**Comment by yarin177** [comment]
I found restarting your computer might help,or trying another wifi

**Comment by gabesw** [comment]
I just hit a few keys while the script said hold on for the first time and ran it over and over quickly and it worked

**Comment by gabesw** [comment]
Just press the enter key when it throws the error and it will work.
