### ISSUE TITLE
Device won't get kicked out

### ISSUE THREAD

**Issue by M1st3rN0Nam3** [k4m4/kickthemout#400]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

<br/ >

Hello,
I'm sorry that I can't give you information like the kernel version now because I'm not at home.

I have an Raspberry pi 3 B+ and I flashed the newest Kali version on it.

I've installed the kickthemout script and did the steps from the README.txt.

I tried to kick my mobile phone out of my home network and the script also detected everything.

My problem is that "spoofing started" was there for about 40 minutes but it didn't kicked my phone out.

Do you know what I could do?

Sorry for my bad English, it isn't my native language.

Thanks in advance
M1st3rN0Nam3

**Comment by k4m4** [comment]
Hi there @M1st3rN0Nam3. Please have a look at my final response to issue #310. Thanks!

**Comment by M1st3rN0Nam3** [comment]
> 
> 
> Hi there @M1st3rN0Nam3. Please have a look at my final response to issue #310. Thanks!

Thank you very much!
I'm sorry haven't seen that one :)
