### ISSUE TITLE
Kamene - Scapy

### ISSUE THREAD

**Issue by gpotter2** [k4m4/kickthemout#409]
Hi @k4m4 (and other kickthemout users :smile:),

I'm a Scapy maintainer, and have bumped into this project because it was linked in https://github.com/k4m4/kickthemout/issues/371 (https://github.com/secdev/scapy/issues/1683)

I've noticed that you were using `kamene`. I'm assuming you were using `scapy-python3` before it was renamed. Please note that `kamene` is NOT an official Scapy version. Quoting https://scapy.net/

> An independent fork of Scapy was created from v2.2.0 in 2015, aimed at supporting only Python3 (scapy3k). The fork diverged, did not follow evolutions and fixes, and has had its own life without contributions back to Scapy. Unfortunately, it has been packaged as python3-scapy in some distributions, and as scapy-python3 on PyPI leading to confusion amongst users. It should not be the case anymore soon. Scapy supports Python3 in addition to Python2 since 2.4.0. Scapy v2.4.0 should be favored as the official Scapy code base. The fork has been renamed as kamene.

### Why this is a problem

There are two issues:
- for you: you are using a version of Scapy that clearly is buggy and not maintained. Development is stopped (or sometimes a few merged PRs now and then) and it's missing many improvements and bug fixes. Moreover we had issues with the owner of this fork trying to mislead users by using a confusing name.
- for us: we get bug reports that we fixed ages ago because some people still use this fork. This wastes some of our time

I'd advise switching to `scapy` = the original Scapy.

Thanks for your time !

**Comment by k4m4** [comment]
Hi there @gpotter2. Thank you for letting us know about this. I'll work on this asap. Thanks again.
