### ISSUE TITLE
Requirements have not been properly satisfied: MacOS Sierra

### ISSUE THREAD

**Issue by centinil** [k4m4/kickthemout#41]
Keep on getting the same issue even after re installing everything.

ERROR: Requirements have not been properly satisfied. Please try running:
	$ sudo pip install -r requirements.txt

If you still get the same error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Requirement already satisfied: pcapy in /usr/local/lib/python2.7/site-packages
$ brew install libdnet scapy
Updating Homebrew...
Warning: libdnet-1.12 already installed
Warning: homebrew/python/scapy-2.3.3 already installed

Doing something wrong?

**Comment by k4m4** [comment]
Check out [Issue #42](https://github.com/k4m4/kickthemout/issues/42) and [Issue #13](https://github.com/k4m4/kickthemout/issues/13). Please let me know if you don't manage to resolve your issue. Thanks!
