### ISSUE TITLE
module 'nmap' has no attribute 'PortScanner'

### ISSUE THREAD

**Issue by kyleanthony1992** [k4m4/kickthemout#412]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Kamene version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**:

**Comment by mgueji** [comment]
I had the same problem, solved by:
```
sudo pip3 uninstall nmap
sudo pip3 install --upgrade python-nmap
```

**Comment by rebl0x3r** [comment]
Run: 

`sudo apt-get install python3-nmap`

This solve it

**Comment by k4m4** [comment]
Closing due to issue author inactivity.
