### ISSUE TITLE
Kali/termux issue 

### ISSUE THREAD

**Issue by Chingo-X** [k4m4/kickthemout#416]
Hello 
I have tried to install kickthemout on termux but it always giving me this issue
I just execute these lines : 
$pkg install git 
$pkg install python2 
$pkg install  nmap 
$git  clone https://github.com/k4m4/kickthemout.git
$cd kickthemout 
$chmod  +x kickthemout.py 
$sudo pip2 install  -r requirements.txt
$sudo python2 kickthemout.py

I installed on Kali and giving me same error 

And if I runs it like this 
It's giving me this error too 
: 
root@localhost:~/kickthemout# ./kickthemout.py

ERROR: Gateway IP could not be obtained. Please enter IP manually.

kickthemout> Enter Gateway IP (e.g. 192.168.1.1):

If I putting my ip manually it making my device restarting .

Iam running Android pie I wish someone help me 
Thanks however 
![Screenshot_20190928-150636_Termux](https://user-images.githubusercontent.com/52953017/65817256-44e3bb80-e205-11e9-8d60-f4089e79e2e7.png)
![Screenshot_20190928-153149_Termux](https://user-images.githubusercontent.com/52953017/65817270-765c8700-e205-11e9-9458-914defdde7ad.png)

**Comment by k4m4** [comment]
Hi there @Chingo-X. Unfortunately, KickThemOut is not compatible with Termux. Thanks.

**Comment by Chingo-X** [comment]
Ok thanks

**Comment by addsssjshsib9179-cmd** [comment]
Hi

**Comment by since198905** [comment]
Hi,how r u,long time no see.
________________________________
