### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by alfaridzf100** [k4m4/kickthemout#418]
I get this problem.
```
# python3 kickthemout.py
Traceback (most recent call last):
  File "kickthemout.py", line 756, in <module>
    defaultInterface = getDefaultInterface()
  File "kickthemout.py", line 154, in getDefaultInterface
    network, netmask, _, interface, address, _ = max(iface_routes, key=lambda item:item[1])
ValueError: max() arg is an empty sequence
```
Help me guysss :(

**Comment by martinfrouin** [comment]
Same error after following the readme on MacOS 10.15.1 to run the `kickthemout.py` script

**Comment by k4m4** [comment]
Hi @tinmar33. Please follow the template when opening a new issue, so that we can help you resolve it. Thank you.

**Comment by martinfrouin** [comment]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

- **OS name & version**: Mac OS 10.15.1
- **Python version**: Python 3.7.6
- **Scapy version**: Version 2.4.3
- **Nmap version**: Version 7.70
- **Link of [Gist](https://gist.github.com/)**: https://gist.github.com/tinmar33/c86fe369619b9d10a5159b3be194a971

**Comment by martinfrouin** [comment]
I just fixed the issue by updating VirtualBox to the last version. Scapy couldn't run properly without it.

**Comment by k4m4** [comment]
@tinmar33 Good to hear that. Thanks!
