### ISSUE TITLE
Can't install scapy on MacOS

### ISSUE THREAD

**Issue by tymscar** [k4m4/kickthemout#42]
The MacOS guide states that I need to install scapy using brew but I cant find the package.

> Error: No available formula with the name "scapy"
> ==> Searching for similarly named formulae...
> Error: No similarly named formulae found.
> ==> Searching taps...
> Error: No formulae found in taps.

I installed scapy from scapy.net and the kickthemout.py script still doesent work:

> Traceback (most recent call last):
>   File "kickthemout.py", line 338, in <module>
>     scanNetwork()
>   File "kickthemout.py", line 72, in scanNetwork
>     hostsList = scan.scanNetwork()
>   File "/Users/oscarmolnar/kickthemout/scan.py", line 69, in scanNetwork
>     return scan_and_print_neighbors(net, interface)
>   File "/Users/oscarmolnar/kickthemout/scan.py", line 30, in scan_and_print_neighbors
>     ans, unans = scapy.layers.l2.arping(net, iface=interface, timeout=timeout, verbose=False)
>   File "/usr/local/lib/python2.7/site-packages/scapy/layers/l2.py", line 700, in arping
>     filter="arp and arp[7] = 2", timeout=timeout, iface_hint=net, **kargs)
>   File "/usr/local/lib/python2.7/site-packages/scapy/sendrecv.py", line 378, in srp
>     a,b=sndrcv(s ,x,*args,**kargs)
>   File "/usr/local/lib/python2.7/site-packages/scapy/sendrecv.py", line 133, in sndrcv
>     r = pks.nonblock_recv()
>   File "/usr/local/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 672, in nonblock_recv
>     p = self.recv(MTU)
>   File "/usr/local/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 653, in recv
>     pkt = self.ins.next()
>   File "/usr/local/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 390, in next
>     s,us = h.getts()
> AttributeError: 'NoneType' object has no attribute 'getts' 

What should I try next?

**Comment by k4m4** [comment]
The same issue has appeared in: [Issue #13](https://github.com/k4m4/kickthemout/issues/13). You probably haven't set up `scapy` correctly. First, you must run `sudo pip install pcapy`, then `brew install libdnet`, and finally `brew install scapy`. It is very possible that `scapy` will ask you to run some commands to successfully set it up. Let me know if this resolved your issue. Thanks.

**Comment by k4m4** [comment]
If you still have any issues, please let me know.

**Comment by tymscar** [comment]
I did just that. Installed pcapy with sudo pip install pcapy. Then i installed libdnet with brew and when I try to install scapy with bre the error I posed above appears.

**Comment by tjcommers** [comment]
I have the same error

**Comment by k4m4** [comment]
Hi there. When installing scapy with brew, did you run the commands that brew instructs you to execute? @tymscar @tjcommers

**Comment by tymscar** [comment]
I didn't get such messages from brew. What did I miss?

**Comment by k4m4** [comment]
Head over to [Issue #54](https://github.com/k4m4/kickthemout/issues/54) for the solution to this issue. Thanks. @dvvedz
