### ISSUE TITLE
Nmap `stopTimeOutClock`

### ISSUE THREAD

**Issue by ceylanb** [k4m4/kickthemout#425]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **Archlinux & 5.4.1**
- **Python 3.8.0**
- **Scapy 2.4.3**
- **Nmap 7.80**

<br/ >

- **Description**:  The error message from Nmap:
```
nmap: Target.cc:503: void Target::stopTimeOutClock(const timeval*): Assertion 'htn.toclock_running == true' failed.
```

The Nmap issue related to this error: https://github.com/nmap/nmap/issues/1361. The issue is still open.

**Comment by k4m4** [comment]
Hi @ceylanb. Seems like the issue has been fixed now. Thanks for bringing it to my attention though.
