### ISSUE TITLE
Spoofing not working!

### ISSUE THREAD

**Issue by hyzo90** [k4m4/kickthemout#43]
Installed everything accordingly . running fine. but it's not kicking the target off.

**Comment by xdavidhu** [comment]
Please provide more information about your os, python enviroment, and your network.

**Comment by hyzo90** [comment]
![ddos](https://cloud.githubusercontent.com/assets/24711785/22290577/f73bdd2a-e344-11e6-94ad-191b047d34ef.jpg)

**Comment by FrostyModz** [comment]
SAME! i do this in CMD: ping 8.8.8.8 -t

run the app, select my computer ip and it says request time out in CMD but i still have internet! idk why

**Comment by xdavidhu** [comment]
@hyzo90 Is your windows machine connected to the 192.168.98.0/24 network?

You can check it with the `ipconfig` command on windows.

**Comment by xdavidhu** [comment]
Try it again after running this command on the Kali machine:

`sudo echo 0 > /proc/sys/net/ipv4/ip_forward`

**Comment by k4m4** [comment]
Please let us know if this resolved your issue. Thanks!

**Comment by nicksedz** [comment]
@FrostyModz @hyzo90 Hey guys, I had this issue too.. I resolved it by going into my virtual box settings, under network, and creating another adapter.

Adapter 2 > Attached to: Bridged Adapter > Name: en1: WiFi.

hope this helps

**Comment by nicksedz** [comment]
I do have a question of my own. I am not able to find a specific IP that im looking for. I can see that the device (iphone) is connected to my network, but kickthemout doesnt find it. sometimes this is solved by hitting ctrl>c to quit it and try it again, but I cant find the device at all. 

Thanks!

**Comment by nicksedz** [comment]
Is there anyway to increase the strength when spoofing? The device I target gets pretty crippled, but sometimes not as much as I would like it. Just a thought. Thanks for making this awesome tool.

**Comment by FrostyModz** [comment]
get something called "NodeMCU" it does the exact same but its an external device. they are all the same meaning they should work

**Comment by sebastianxcf** [comment]
Hi, I'm on ubuntu 14.04. 
I trying to kick someone out, but not working. I've the ip of the target, and it's in the same wifi. I have checked with nmap. I attch a scrennshot. Not sure what is happening. Also not all the devices that are showed with nmap are in the list of posible target for kickthemout .

Thanks in advance.


![selection_092](https://cloud.githubusercontent.com/assets/23262528/23102854/29f7603e-f6b1-11e6-91d1-668033cc0825.jpg)

**Comment by rraj7444** [comment]
I have done everything according to kickthemout official page and also all  requirement has been already satisfied and i  have make  kickthemout.py
As executable but when i run it takes too much time even it does not work ??Can any one help me

**Comment by ppasnam** [comment]
I've tried many times with the Kickthemout tool but there are too many parts that don't work. First of all it can't scan devices properly, it only shows three devices even though I have more than five devices connected to my network in my house (they have wrong ip). It can't disconnect any device even after I've waited for more than twenty minutes. Do I need a wifi card for this tool to work properly? Or any step I need to take? Can you help me???

**Comment by ppasnam** [comment]
kickthemout is a tool that I like very much and it works for me, can you please fix these problems
