### ISSUE TITLE
No Module named nmap

### ISSUE THREAD

**Issue by jomonjames** [k4m4/kickthemout#430]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**:

**Comment by hiddenwishes** [comment]
Got the same issue

**Comment by elitex45** [comment]
type this `apt-get install python-nmap`

**Comment by MarcoGMB** [comment]
i have this problem fixed with this code:

> `apt-get install python-nmap`

 than i had a other problem :

> `No module named request`

pls help...

**Comment by CaraTortu** [comment]
Do
1. git clone https://github.com/k4m4/kickthemout.git
2. cd kickthemout
3. sudo pip uninstall -r requirements.txt
4. sudo pip3 uninstall -r requirements.txt
5. sudo -H pip install -r requirements.txt
6. sudo -H pip3 install -r requirements.txt
7. sudo chmod +x kickthemout.py
8. sudo python3 kickthemout.py

**Comment by k4m4** [comment]
Closing due to issue author inactivity.
