### ISSUE TITLE
No module names 'scapy'

### ISSUE THREAD

**Issue by ghost** [k4m4/kickthemout#434]
Hello, when trying to run kickthemout.py im getting these lines :

     RootUser@LinuxMint/2020TI_I9:~/kickthemout$ python3 kickthemout.py

     ERROR: KickThemOut must be run with root privileges. Try again with sudo:
	     $ sudo python3 kickthemout.py

#Lets run it with sudo then

     RootUser@LinuxMint/2020TI_i9:~/kickthemout$ sudo python3 kickthemout.py

     ERROR: Requirements have not been satisfied properly. Please look at the README file for 
     configuration instructions.

     If you still cannot resolve this error, please submit an issue here:
	     https://github.com/k4m4/kickthemout/issues

    Details: No module named 'scapy'

# I have tried to uninstall the requirements, upgrade pip3 then reinstall and here is the result

RootUser@LinuxMint/2020TI_I9:~/kickthemout$ sudo pip3 install -r requirements.txt

WARNING: The directory '/home/bangajuice/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting scapy
  Downloading scapy-2.4.3.tar.gz (905 kB)
     |████████████████████████████████| 905 kB 519 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pmwoj3sz/scapy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pmwoj3sz/scapy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-pmwoj3sz/scapy/pip-egg-info
         cwd: /tmp/pip-install-pmwoj3sz/scapy/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

#Could i please get some help ?

**Comment by fenikurniawan5** [comment]
help me

**Comment by kali-naz** [comment]
I have the same issue and still i'm not able to run the  script

**Comment by k4m4** [comment]
Closing since this issue seems irrelevant to KickThemOut. I would suggest opening an issue on [`scapy`](https://github.com/secdev/scapy)'s repo if you are unable to find a solution online. Thanks.
