### ISSUE TITLE
No module named request

### ISSUE THREAD

**Issue by MarcoGMB** [k4m4/kickthemout#436]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**: 

I had the problem with the error :

> `No module named nmap` 

I have fixed it with :

> `apt-get install python-nmap`

and where i started it again than i had this problem :

> `No module named request`

I hope you can help me with that error...

**Comment by yairster** [comment]
I have the same issue!! Please help

**Comment by yairster** [comment]
kali@kali:~/Desktop/kickthemout$ python kickthemout.py 

ERROR: KickThemOut must be run with root privileges. Try again with sudo:
        $ sudo python3 kickthemout.py

kali@kali:~/Desktop/kickthemout$ sudo python kickthemout.py 

ERROR: Requirements have not been satisfied properly. Please look at the README file for configuration instructions.

If you still cannot resolve this error, please submit an issue here:
        https://github.com/k4m4/kickthemout/issues

Details: No module named request
kali@kali:~/Desktop/kickthemout$

**Comment by 3xploitGuy** [comment]
I was having the same issue, try these commands
sudo -H pip3 install -r requirements.txt
sudo python3 kickthemout.py
and the problem will be solved.

**Comment by Pirry009** [comment]
> I was having the same issue, try these commands
> sudo -H pip3 install -r requirements.txt
> sudo python3 kickthemout.py
> and the problem will be solved.

root@kali:~/Descargas/kickthemout-master# sudo -H pip3 install -r requirements.txt
sudo: pip3: command not found

**Comment by giagos** [comment]
follow this and then re do as instructed in the above posts
https://www.kalilinux.in/2019/08/install-python3-in-kali-linux.html
hope this helps

**Comment by k4m4** [comment]
Closing since this error seems irrelevant to KickThemOut. Thanks.
