### ISSUE TITLE
module 'nmap' has no attribute 'PortScanner'

### ISSUE THREAD

**Issue by xprotector** [k4m4/kickthemout#437]
ERROR: Network scanning failed. Please check your requirements configuration.

If you still cannot resolve this error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

Details: module 'nmap' has no attribute 'PortScanner'

**Comment by CaraTortu** [comment]
What I did was install it normally but before doing 'sudo -H pip3 install -r requirements.txt' I did 'sudo  pip3 uninstall -r requirements.txt'. Then you type 'sudo chmod +x kickthemout.py' and finally you type 'sudo python3 kickthemout.py' and it works!! I hope that helped. (I took 5 hours to figure this out)

**Comment by k4m4** [comment]
Closing due to issue author inactivity.
