### ISSUE TITLE
No Module Named "Scapy"

### ISSUE THREAD

**Issue by kali-naz** [k4m4/kickthemout#444]
## Checklist for submitting an issue to `KickThemOut`:

- [ ] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [ ] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [ ] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**:

**Comment by kali-naz** [comment]
please guys help to resolve this error no module named scapy I have tried every possible solution but still i'm getting the same Error

**Comment by Ckrielle** [comment]
What have you tried so far? Have you run `sudo -H pip3 install -requirements.txt`?

**Comment by ghost** [comment]
Error 404 
https://pypi.org/simple/requirements-txt/

**Comment by 911didbush420** [comment]
i cant ever open the read me so i cant fix this issue

**Comment by CaraTortu** [comment]
Do
1. git clone https://github.com/k4m4/kickthemout.git
2. cd kickthemout
3. sudo pip uninstall -r requirements.txt
4. sudo pip3 uninstall -r requirements.txt
5. sudo -H pip install -r requirements.txt
6. sudo -H pip3 install -r requirements.txt
7. sudo chmod +x kickthemout.py
8. sudo python3 kickthemout.py

**Comment by k4m4** [comment]
Closing due to issue author inactivity.
