### ISSUE TITLE
Cannot arp-spoof devices via Kali 2020.1

### ISSUE THREAD

**Issue by notfun11** [k4m4/kickthemout#447]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: Kali & kali GNU/Linux Rolling release 2020.1
- **Python version**. python3 most recent update
- **Scapy version**: python-scapy 2.4.3-310
- **Nmap version**: nmap 7.80
- **Link of [Gist](https://gist.github.com/)**: I have no idea how to make this gist. I have to use my phone to write all this

<br/ >

- **Description**: You closed my issue in one day without me being able to even reply. I dont know how to use the packets **-p** The thing is, its called kickthemout but it kicks no one. Ive tried kicking Ps4, xbox, samsung android, even a pc. I need more details to make this do what its supposed to do and kick them out not slow them down. And please dont close the issue because it is not resolved, and im not able to re-open it after you close it. I have to start a new issue and thats part of github rules. Ive given you all the info i can. I dont know how to make a gist but i literally have re-done everything from the start by your website for debian https://nikolaskama.me/kickthemoutproject/

**Comment by k4m4** [comment]
Hey @notfun11. I've re-opened your previous issue - please paste this information there so that we can avoid duplicates. Thanks.
