### ISSUE TITLE
Not working under Windows

### ISSUE THREAD

**Issue by piorrro33** [k4m4/kickthemout#45]
Hello,
I've installed the requirements using `pip install -r requirements.txt` but it won't work because it says it's missing requirements. I've checked and scapy is actually installed.
Any way to fix this?
Thank you in advance!

**Comment by k4m4** [comment]
Hi there. KickThemOut has been developed to operate with Windows and Mac OS X operating systems. Windows is not within the compatibility range. I would suggest installing it in a Linux environment. Thanks!
