### ISSUE TITLE
pip Problem

### ISSUE THREAD

**Issue by Realmadrid133** [k4m4/kickthemout#455]
## Checklist for submitting an issue to `KickThemOut`:

- [ ] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [ ] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [ ] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**:

**Comment by Realmadrid133** [comment]
Every time when i do  pip -r requirements.txt it comes comment is not founded

**Comment by Bobowonnell** [comment]
manually install requirements then

**Comment by Realmadrid133** [comment]
How can i knstall them or where can i find them

**Comment by Bobowonnell** [comment]
sudo apt-get install python-nmap
sudo apt-get install netifaces
sudo apt-get install scapy

If you are running anything that doesn't recognize those commands then idk what to tell you. If they don't work then tell me :) good luck

**Comment by Bobowonnell** [comment]
also can you tell me if the kickthemout is working properly for you

**Comment by Realmadrid133** [comment]
But can you write me in wich row and waht you do in the. terminal

Yeah sure

**Comment by Bobowonnell** [comment]
Do you mean for the whole proccess

**Comment by Realmadrid133** [comment]
Yeah i think i do somthing wrong

**Comment by Bobowonnell** [comment]
do you have discord?

**Comment by Realmadrid133** [comment]
Yes wait

**Comment by Bobowonnell** [comment]
kk

**Comment by Realmadrid133** [comment]
Wait i download now then i text you my tag

**Comment by Bobowonnell** [comment]
ok

**Comment by Bobowonnell** [comment]
my discord is BOP BOP#9933

**Comment by Realmadrid133** [comment]
https://discord.gg/QT4XxQ

**Comment by Realmadrid133** [comment]
Can you come here i dont kno discord much

**Comment by Bobowonnell** [comment]
ok

**Comment by k4m4** [comment]
Hey @Bobowonnell and @Realmadrid133. This issue is a mess so I am deleting it. I hope you have been able to solve the problem. Otherwise, please create a new issue with a more descriptive description and title. Thanks!
