### ISSUE TITLE
local variable 'f' referenced before assignment

### ISSUE THREAD

**Issue by athallarizky** [k4m4/kickthemout#457]
Is it syntax error? I'm trying to open it on ubuntu19 for termux.
![Screenshot_2020-05-29-06-08-31-639_com termux](https://user-images.githubusercontent.com/30741314/83203140-fbbc8080-a172-11ea-9003-af68f4c6d630.jpg)

**Comment by ankit2001** [comment]
It seems you have not used the command sudo -H pip3 install -r requirements.txt
or you have some version issues of dependencies.

**Comment by athallarizky** [comment]
I already did it
![Screenshot_2020-06-01-19-44-24-621_com termux](https://user-images.githubusercontent.com/30741314/83410357-71a93c00-a440-11ea-8844-3b4d985fe793.jpg)

**Comment by ankit2001** [comment]
If it was a syntax error then  it also should not work on my pc, may be you have some issues regarding your python package in termus or something else.

**Comment by HubbyDeb** [comment]
same problem any help

**Comment by k4m4** [comment]
Hi @athallarizky. KickThemOut has not been tested in and is not compatible with Android devices. If you have any other questions, please feel free to re-open this issue. Thanks!
