### ISSUE TITLE
Scapy installs, but kickthemout.py says it didn't

### ISSUE THREAD

**Issue by denisgabriel** [k4m4/kickthemout#46]
Hi, so I installed scapy, but when I try to run the script, it gives me this errors:
![cmd-windows](https://cloud.githubusercontent.com/assets/23343454/22294864/913aa5d2-e31d-11e6-84f5-4902f9ae4403.png)

**Comment by piorrro33** [comment]
Managed to get it to work installing Winpcap. Might need pyreadline and matplotlib.

**Comment by k4m4** [comment]
So you managed to make it work successfully with `Winpcap`? @piorrro33

**Comment by piorrro33** [comment]
@k4m4 Just updated my comment.

**Comment by k4m4** [comment]
What do you mean "it crashes"? Does it exit the script? Could you provide a screenshot?

**Comment by piorrro33** [comment]
There you go. https://a.pomf.cat/czpvqw.png

**Comment by k4m4** [comment]
This - again - is a `scapy` issue. Unfortunately, I don't see many things we can do to resolve this Windows problem. I will re-visit is later on during the day though. Thanks.

**Comment by denisgabriel** [comment]
Would it work better on linux, let's say kali?

**Comment by k4m4** [comment]
Of course. KickThemOut has been developed with Linux & Mac OS X compatibility. @denisgabriel

**Comment by denisgabriel** [comment]
Alright then. @k4m4

**Comment by k4m4** [comment]
Possibly. However, I doubt it. Thanks! @denisgabriel
