### ISSUE TITLE
Kali Linux on Raspberry Pi - kickthemout issue

### ISSUE THREAD

**Issue by Spinner01** [k4m4/kickthemout#47]
Having serious issues getting kickthemout to work have cloned it from github, and downloaded scapy and still not working. Have tried to uninstall scapy but wont let me I try running the command "sudo pip uninstall scapy" and I get a message "Not uninstalling scapy at /usr/lib/python2.7/dist-packages, outside enviroment/usr. I have tried a lot of the solutions given to no avail. Any help would be greatly appreciated!

Edit - Works fine on a Kali Linux Virtual Machine, could it be to do with the pi being a fresh install or something?

**Comment by xdavidhu** [comment]
It's probably because Scapy is installed on Kali out of the box.

Try removing it with apt-get:
`sudo apt-get remove scapy`

And after it reinstalling it with pip:
`sudo pip install scapy`

**Comment by Spinner01** [comment]
Thanks for getting back to me, but that is still not working. I try to run "python kcikthemout.py" and I get the same error " Requirements have not been properly satisfied. Please try running.."

**Comment by TheDukeOfDeath** [comment]
I would have to guess that it doesn't work on your RPI, because it is ARM.

**Comment by xdavidhu** [comment]
It works on RPI for sure, running fine for me on Raspbian.

**Comment by Met4crypt** [comment]
same here. doesnt work. This its maby because of different python release? will try to "rewrite" some of the errors i got earlyer and try again. Il post if i fix it :)

**Comment by k4m4** [comment]
Sounds good. Let us know how it goes. :)
@Met4crypt

**Comment by 0rigin5** [comment]
did yhis ever work for you? im planning on doing this on my pi

**Comment by Met4crypt** [comment]
Forgot the whole thing and never tried. 

I think its the Python versions or something. 

Sendt fra min iPhone
