### ISSUE TITLE
network error when running kickthemout.py

### ISSUE THREAD

**Issue by dvvedz** [k4m4/kickthemout#48]
Hi, as you can see from the title i having problems running the program.
im getting this error: ERROR: Network scanning failed. Please check your requirements configuration.
i have installed everything. I did install scapy with this command: sudo easy_install scapy can this be the problem?
im on mac os.

Thanks in advanced.

**Comment by xdavidhu** [comment]
Hey, have you installed libdnet/pcapy?

Try running KickThemOut after these commands:
```
sudo pip install pcapy

brew install libdnet scapy

sudo pip install -r requirements.txt
```

**Comment by dvvedz** [comment]
i have downloaded everything but libdnet scapy, because I'm getting:
 Error: No available formula with the name "scapy". it can't bet find or
something.


2017-01-26 19:56 GMT+01:00 David Schütz <notifications@github.com>:

**Comment by xdavidhu** [comment]
Try updating brew, and try again:

```
brew doctor
brew update
brew install libdnet scapy
```

**Comment by dvvedz** [comment]
brew update says its up to date.

this is what I'm getting from brew doctor.

Please note that these warnings are just used to help the Homebrew
maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5m-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/dnet.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libdnet.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libdnet.a

Warning: /usr/bin occurs before /usr/local/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:
  2to3

Consider setting your PATH so that /usr/local/bin
occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/share/man/man8/prlexec.8

2017-01-26 20:10 GMT+01:00 David Schütz <notifications@github.com>:

**Comment by Dedados** [comment]
I have the exact same issue! I get the same error when trying to $ brew install scapy. Both pcapy and libdnet have been install though. Whenever I run the program I get the same ERROR: network scanning failed...

I ran brew doctor and had similar issues to yours, I fixed all I could apart from this one:

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

**Comment by Dedados** [comment]
This worked for me:

> First of all type in your cmd:

pip install scapy
pip install git+git://github.com/hellais/pypcap.git
brew install --with-python libdnet

Then,

mkdir -p ~/Library/Python/2.7/lib/python/site-packages
echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> ~/Library/Python/2.7/lib/python/site-packages/homebrew.pth

Enjoy


https://github.com/k4m4/kickthemout/issues/54

**Comment by k4m4** [comment]
Glad to hear that @Dedados. Head over to [Issue #57](https://github.com/k4m4/kickthemout/issues/54) for the solution to this issue. Thanks. @dvvedz

**Comment by Dedados** [comment]
I think you mean issue 54?

**Comment by k4m4** [comment]
Yes. That is correct. @Dedados (typo.)
