### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by Petetheodddog** [k4m4/kickthemout#49]
(macOS) 
After downloading the requirements I am still unable to run kickthemout.py this is what was dispayed in my terminal window:

<img width="639" alt="screen shot 2017-01-25 at 11 16 20 pm" src="https://cloud.githubusercontent.com/assets/6750242/22309552/57e10ab0-e354-11e6-8e8c-86f1b408ac1b.png">

**Comment by FrostyModz** [comment]
do u have skype? i had this same issue and fixed it

**Comment by k4m4** [comment]
Look at [Issue #13](https://github.com/k4m4/kickthemout/issues/13). Let me know if this resolves your issue. Thanks.
