### ISSUE TITLE
Always says I am offline even if I am online and sometimes it shows and error

### ISSUE THREAD

**Issue by scratchusernamemrtbts** [k4m4/kickthemout#496]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**:Mac OS Big Sur beta 11.3 beta 7 
- **Python version**:3.9.1 
- **Scapy version**:2.4.4 
- **Nmap version**:7.91 
- **Link of [Gist](https://gist.github.com/scratchusernamemrtbts/a5813e38c8aa368b6aaf398b494f7816)**: 

<br/ >

- **Description**: 
it always say that I am offline
<img width="544" alt="ภาพถ่ายหน้าจอ 2564-04-12 เวลา 13 14 06" src="https://user-images.githubusercontent.com/66320961/114348599-f7cdfd00-9b90-11eb-9112-cfb1617f1dbe.png">
and sometimes it gives me this error
<img width="638" alt="ภาพถ่ายหน้าจอ 2564-04-12 เวลา 13 14 23" src="https://user-images.githubusercontent.com/66320961/114348633-01576500-9b91-11eb-8e9b-a0d28e42e608.png">

**Comment by scratchusernamemrtbts** [comment]
but I can run it normally in raspberry pi 4

**Comment by Jason9477** [comment]
I'm meeting the same problem with macOS so I just fix some code here and it works
 `# make sure there is an internet connection
def checkInternetConnection():
    try:
        urlopen('https://github.com', timeout=3)
        return True
    except URLError as err:
        return True
    except KeyboardInterrupt:
        shutdown()

`

**Comment by scratchusernamemrtbts** [comment]
me when i didn't see the reply for 1 year

**Comment by scratchusernamemrtbts** [comment]
oh my god i just found this issue and somehow found that i'm very stupid
(i can easily edit the code to fix it and also the no internet connection was a macos beta bug)
