### ISSUE TITLE
Not really working

### ISSUE THREAD

**Issue by FrostyModz** [k4m4/kickthemout#50]
Ok, i am on Mac OS Sierra. The app runs perfectly fine, i ping 8.8.8.8 on my windows laptop and then use the third option to kick everyone off. The windows computer says Request Time Out but i can still go to google and every other website. Do i need an external wifi card (On of those USB ones) or what? I dont know why it stops pinging but i can still go to google. happens on my phone and on my PS3. I just cant connect to PSN but i still have internet connection (DNS error when connecting to PSN)

**Comment by k4m4** [comment]
That sounds exceptionally bizarre. This shouldn't be possible. Are you still experiencing this issue?

**Comment by FrostyModz** [comment]
Yes I am. I dont know why.

**Comment by xdavidhu** [comment]
Try again after this command:

`sudo echo 0 > /proc/sys/net/ipv4/ip_forward
`

**Comment by k4m4** [comment]
Please let us know if this resolved your issue. Thanks! @FrostyModz

**Comment by FrostyModz** [comment]
im on mac. not cally

**Comment by FrostyModz** [comment]
Kali*
