### ISSUE TITLE
Crash all network

### ISSUE THREAD

**Issue by Hugo1380** [k4m4/kickthemout#51]
Hi

When I select a device, it will drop correctly but when I stop it, all my network goes down except the device selected.

**Comment by Hugo1380** [comment]
Any news ?

**Comment by xdavidhu** [comment]
@Hugo1380 Is the issue still reproducible?

If yes, how long does it take your network to recover? Or is it even recovers?

**Comment by AmauryOrtega** [comment]
@xdavidhu @k4m4 I have the same problem, the installation of requirements went smoothly but if I try to run `sudo python2 kickthemout.py` (Arch Linux user) Sometimes, it detects the gateway IP, some times it doesn't. In either case, all the network activity crashes. Maybe is something related with the security options on my router (Dlink DIR-810L) or the fact that I'm connected on wireless.

**Comment by xdavidhu** [comment]
@AmauryOrtega What do you mean by "all the network activity crashes"? Nobody can connect to the internet? It happens after re-arping? If not, when?

**Comment by AmauryOrtega** [comment]
All the network activity on my computer crashes, any other computer on the
network remains fine. The problem happens before any ARP happens, at least
that's why I think

**Comment by k4m4** [comment]
Hi guys. We've made a few changes to KickThemOut. Does this issue still occur?
Thanks.

**Comment by AmauryOrtega** [comment]
The issue has been fix. Thanks for the attention.

**Comment by k4m4** [comment]
Of course. :)
