### ISSUE TITLE
ERROR: It seems that you are offline. Please check your internet connection.

### ISSUE THREAD

**Issue by cyb3rspace** [k4m4/kickthemout#513]
'''/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/scapy/layers/ipsec.py:471: CryptographyDeprecationWarning: Blowfish has been deprecated
  cipher=algorithms.Blowfish,
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/scapy/layers/ipsec.py:485: CryptographyDeprecationWarning: CAST5 has been deprecated
  cipher=algorithms.CAST5,

ERROR: It seems that you are offline. Please check your internet connection.'''

I get this error message on Mac despite being online.

**Comment by benjaminsabella** [comment]
Try this
`def checkInternetConnection():
    try:
        urlopen('https://github.com', timeout=3)
        return True
    except URLError as err:
        return True
    except KeyboardInterrupt:
        shutdown()`
