### ISSUE TITLE
Can't run the it 

### ISSUE THREAD

**Issue by Tarektouati** [k4m4/kickthemout#52]
I can't run the kickthemout.py, but i have  every things installed properly
![capture d ecran 2017-01-27 a 10 40 43](https://cloud.githubusercontent.com/assets/19335073/22366506/624b9c20-e47d-11e6-80a4-eeb231a9b87f.png)

**Comment by k4m4** [comment]
Hi there. Check out the following issues: [#13](https://github.com/k4m4/kickthemout/issues/13), [#7](https://github.com/k4m4/kickthemout/issues/7) & [#10](https://github.com/k4m4/kickthemout/issues/10). Please let me know if this resolves your issue. Thanks.
