### ISSUE TITLE
Unable to Install - Mac OS Siera

### ISSUE THREAD

**Issue by LeoZango** [k4m4/kickthemout#53]
I get this after typing in the first command in terminal:

sudo pip install pcapy

https://gyazo.com/8cbe43fb0bf73169bca29a739a667923

and this after running the second command

brew install libdnet scapy

https://gyazo.com/2014df722bc7871684a9a9baeb036bfc

I think I have installed homebrew correctly before trying the above commands.

Any help would be greatly appreciated.

Thanks

**Comment by k4m4** [comment]
Hi there. Check out the following issues: [#13](https://github.com/k4m4/kickthemout/issues/13), [#7](https://github.com/k4m4/kickthemout/issues/7) & [#10](https://github.com/k4m4/kickthemout/issues/10). Please let me know if this resolves your issue. Thanks.

**Comment by LeoZango** [comment]
#13 has enabled me to get as far as running the script.
Now I have the error 

https://gyazo.com/914dbb66880b7de9dec10603069ff05d

after typing 

sudo python kickthemout.py

Thanks for the help

**Comment by LeoZango** [comment]
Now I've managed to get the stage of entering my gateway IP.
But it now says...

https://gyazo.com/cd817669b0cc71c68fcfc5fd93f47ac9
