### ISSUE TITLE
MacOS Sierra: ERROR: Network scanning failed.

### ISSUE THREAD

**Issue by centinil** [k4m4/kickthemout#54]
I have followed up how to properly uninstall and install everything, up to that everything is okay until i ran
$ sudo python kickthemout.py

ERROR: Network scanning failed. Please check your requirements configuration.

How can i fix this issue? Thanks in advance.

**Comment by LeoZango** [comment]
Having the same issue.
I'll watch this thread.
Don't bother replying on mine.
Thanks

**Comment by inside-shellshock** [comment]
First of all type in your cmd:

_pip install scapy
pip install git+git://github.com/hellais/pypcap.git
brew install --with-python libdnet_

Then,

_mkdir -p ~/Library/Python/2.7/lib/python/site-packages
echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> ~/Library/Python/2.7/lib/python/site-packages/homebrew.pth_

Enjoy

**Comment by LeoZango** [comment]
Thanks, the above solution worked though I'm not sure the script is actually working on my network.
I'll try again tomorrow but even when I kick all devices nothing happens.

**Comment by k4m4** [comment]
Thank you for your support @inside-shellshock !

**Comment by tymscar** [comment]
This actually helped. The script runs this time around but just as @LeoZango mentioned, it doesn't really do anything on my network.

**Comment by margoober** [comment]
Thank you so much!!

**Comment by arismelachroinos** [comment]
when i type brew install --with-python libdnet      i get bash: brew: command not found
  am i missing something?

**Comment by k4m4** [comment]
You have to install brew first:
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`.
@arismelachroinos
