### ISSUE TITLE
Network Scanning Failed

### ISSUE THREAD

**Issue by Tarektouati** [k4m4/kickthemout#56]
Every things installed but doesn't work 
How can i fix this issue? Thanks in advance.
![capture d ecran 2017-01-29 a 16 45 46](https://cloud.githubusercontent.com/assets/19335073/22405424/a8dc4236-e642-11e6-9109-4c4b33fa40c8.png)

**Comment by centinil** [comment]
same thing is happening to me right now :c

**Comment by LeoZango** [comment]
same but I'm running on mac.

**Comment by Tarektouati** [comment]
i 'm running it on macbook air 11" with macOS Sierra 👍

**Comment by k4m4** [comment]
Hi there. We are working on this. Please follow [Issue #54](https://github.com/k4m4/kickthemout/issues/54) for the solution to this issue. Thanks.
