### ISSUE TITLE
"No vendor" showing only 3 IPs

### ISSUE THREAD

**Issue by centinil** [k4m4/kickthemout#59]
Manage to set up Ubuntu in  a VirtualBox. Tried running the python script and this happened. 

![no vendor](https://i.gyazo.com/ff8524ea8561d1b6d42d889c49623579.png)

Does this mean the script does not work with this type of network?

**Comment by xdavidhu** [comment]
No, KickThemOut will probably work on your network.

"No vendor" just means that the mac resolver service wasn't able to resolve these mac addresses to vendors. (www.macvendors.co)

**Comment by centinil** [comment]
So you think its better installing it on a dual boot instead of a VM?

**Comment by razbaa** [comment]
Try to use the bridged interface if you really want to see the vendor name interface within your LAN.

**Comment by k4m4** [comment]
KickThemOut will definitely work better on a dual boot system. Thanks.
