### ISSUE TITLE
"DefaultGatewayMac" is not defined

### ISSUE THREAD

**Issue by centinil** [k4m4/kickthemout#60]
When I closed the program.

![](https://i.gyazo.com/af65aa02c5c9540fd9fbefa4ddfe32fc.png)

Any ideas?

**Comment by k4m4** [comment]
This issue should be fixed by now. Please let us know if the issue has been resolved.

**Comment by centinil** [comment]
Yes that issue did not show up, thanks

**Comment by xdavidhu** [comment]
@centinil Happy to hear that!

**Comment by k4m4** [comment]
Good to know. Thank you for your feedback. @centinil
