### ISSUE TITLE
macOS Sierra 10.12.2 - Requirements not satisfied

### ISSUE THREAD

**Issue by d0cm0d** [k4m4/kickthemout#61]
I installed python via brew:
```
$ pip --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

Afterwards I installed requirements as described. But I still get the following error:
```
$ sudo python kickthemout.py 

ERROR: Requirements have not been properly satisfied. Please try running:
	$ sudo pip install -r requirements.txt

If you still get the same error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

```

If I try to install requirements again, I get the following:
```
$ sudo pip install -r requirements.txt
Requirement already satisfied: scapy in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
```

**Comment by steel99xl** [comment]
Hay I am not sure how much this will help but this helped to fix that problem with me

export PYTHONPATH=brew --prefix/lib/python2.7/site-packages:$PYTHONPATH

**Comment by d0cm0d** [comment]
Adding the following to my ~/.bash_profile did **not** fix the problem for me:
`export PYTHONPATH='brew --prefix'/lib/python2.7/site-packages:$PYTHONPATH`

But thank you anyway.

**Comment by steel99xl** [comment]
just to ask did you run the command i sent or did you just try to add it to the profile

**Comment by d0cm0d** [comment]
I tried both. Neither did work :(

**Comment by tjcommers** [comment]
Hi, I have the same problem running MacOS Yosemite 10.10.5 . If you have any ideas please let us know. Thanks.

**Comment by k4m4** [comment]
Hi there. Check out the following issues: [#13](https://github.com/k4m4/kickthemout/issues/13), [#7](https://github.com/k4m4/kickthemout/issues/7) & [#10](https://github.com/k4m4/kickthemout/issues/10). Please let me know if this resolves your issue. Thanks.
