### ISSUE TITLE
Install Error on Mac OS 10.12.2

### ISSUE THREAD

**Issue by milanb123** [k4m4/kickthemout#62]
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-syI5kh/scapy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2JgQK1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-syI5kh/scapy/

This error keeps occurring when trying to install the requirements.

**Comment by k4m4** [comment]
Hi there. Check out the following issues: [#13](https://github.com/k4m4/kickthemout/issues/13), [#7](https://github.com/k4m4/kickthemout/issues/7) & [#10](https://github.com/k4m4/kickthemout/issues/10). Please let me know if this resolves your issue. Thanks.
