### ISSUE TITLE
Installing requirements error on OS X

### ISSUE THREAD

**Issue by 9arenam** [k4m4/kickthemout#63]
After running "python kickthemout.py", I get this error:
ERROR: Requirements have not been properly satisfied. Please try running:
	$ sudo pip install -r requirements.txt
I've done this and it gives me this error:
Requirement already satisfied: scapy in /anaconda/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Is kickthemout not recognizing that I already have installed scapy?

**Comment by heeem321** [comment]
soo from what i saw up until now you have to not install scapy through pip but rather install scapy through home brew, which also does not seem to work at least for me, i get this message that says the formula does not exist.

in my case what happened was that i installed scapy through the requirements.txt file the other stuff through homebrew but after all that is done i get a network error.

**Comment by steel99xl** [comment]
try what is discussed in the link

https://github.com/k4m4/kickthemout/issues/57

**Comment by k4m4** [comment]
Hi there. Check out the following issues: [#13](https://github.com/k4m4/kickthemout/issues/13), [#7](https://github.com/k4m4/kickthemout/issues/7) & [#10](https://github.com/k4m4/kickthemout/issues/10). Please let me know if this resolves your issue. Thanks.
