### ISSUE TITLE
Installation error, python install (MAC)

### ISSUE THREAD

**Issue by 123bo456** [k4m4/kickthemout#64]
Hi there, 

When I try to install the program in terminal using a mac, it says "ERROR: Requirements have not been properly satisfied. Please try running:sudo pip install -r requirements.txt".

I have tried running this command, however it then it refers me to this site, because i am still getting the same error.

What can i do about this?

Thanks in advance!

**Comment by k4m4** [comment]
Hi there. Check out the following issues: [#13](https://github.com/k4m4/kickthemout/issues/13), [#7](https://github.com/k4m4/kickthemout/issues/7) & [#10](https://github.com/k4m4/kickthemout/issues/10). Please let me know if this resolves your issue. Thanks.

**Comment by 123bo456** [comment]
Hi there,

Thank you, it works, however it now says zero hosts are up when i have several online. What can i do about this?

Thank you for you help!
Really appreciate it!

**Comment by k4m4** [comment]
It should work now. Could you test it and let me know please? @123bo456
