### ISSUE TITLE
ERROR: Requirements have not been properly satisfied.

### ISSUE THREAD

**Issue by teunvw14** [k4m4/kickthemout#66]
I'm trying to run the script on a Macbook. Even after trying "sudo pip install -r requirements.txt", it still gives the same error. While installing I did notice that when trying to install scapy it didn't find it: 
               
              brew install scapy
Error: No available formula with the name "scapy" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
I hope someone has found a solution.

**Comment by caiobep** [comment]
You actually need to use pip (Python Package Index) to install scapy. try 
`pip install scapy`
couldn't get it to work either, but it's certainly not a problem with scapy 😄

**Comment by k4m4** [comment]
Hi there. Check out the following issues: [#13](https://github.com/k4m4/kickthemout/issues/13), [#7](https://github.com/k4m4/kickthemout/issues/7) & [#10](https://github.com/k4m4/kickthemout/issues/10). Please let me know if this resolves your issue. Thanks.
