### ISSUE TITLE
Nothing happens when typing "python kickthemout.py"

### ISSUE THREAD

**Issue by Nitomake** [k4m4/kickthemout#67]
I am using Kali Linux on a Usb bootable drive on a macbook at my school, everything works until I try to run it with python kickthemout.py then nothing happens. Any ideas/help? Thanks!﻿

I am also on the desktop/kickthemout# so that shouldn't be the problem.

NOTE: I might not have done the install requirements part... I'm gonna try that later
EDIT: Nope that didn't do anything, it worked at home, with the USB stick and all. But it doesn't work in school. It just goes blank.

**Comment by kpjVideo** [comment]
same here :/

**Comment by k4m4** [comment]
KickThemOut must be run with root privileges. Try running `$ sudo python kickthemout.py` and if this error still occurs, try entering Control+C (^C) which might display a message indicating your error.

**Comment by k4m4** [comment]
Please let us know if this helped you resolve this issue. @Nitomake @kpjVideo

**Comment by Nitomake** [comment]
Thanks alot I will try it out tomorrow when I get back! @k4m4
