### ISSUE TITLE
Requirements have not been properly satisfied

### ISSUE THREAD

**Issue by thekadenh** [k4m4/kickthemout#69]
It won't let me run kickthemout. I've done all of your steps, and it says sudo is installed:

Requirement already satisfied: scapy in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 1))

But, when I tried to run the brew install libdnet scapy, this came up:

Error: No available formula with the name "scapy" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

I don't know how to make this work. I installed the latest version of homebrew before this, but it's still giving me these errors. Please help! I'm using the latest version of mac os x.

**Comment by k4m4** [comment]
Hi there. Check out the following issues: [#13](https://github.com/k4m4/kickthemout/issues/13), [#7](https://github.com/k4m4/kickthemout/issues/7) & [#10](https://github.com/k4m4/kickthemout/issues/10). Please let me know if this resolves your issue. Thanks.
