### ISSUE TITLE
can anyone actually use it ? 

### ISSUE THREAD

**Issue by kashkalik** [k4m4/kickthemout#70]
Hi guys, 

I have two computers, one mac os, the other ubuntu. 

I tried on mac, and I got the following error :

" ERROR: Requirements have not been properly satisfied. Please try running. " 

But I am pretty sure the requirements are already installed. 

I tried on Ubuntu, and was able to run the program. But, the script just kept waiting , and after like 30 minutes, nothing happened. Not a single computer is kicked off. 

So wondering, is anyone able to actually use this ?

**Comment by k4m4** [comment]
You tell me:
- https://www.youtube.com/results?search_query=%22kickthemout%22

**Comment by k4m4** [comment]
Hello again. As you can see from the multiple videos, yes, people have 'actually used it'. Next time, when you want to ask a question, please do it in a more respectful manner, with a more respectful title. We have spent a lot of our free time to make this open source tool. Thank you. @kashkalik

**Comment by k4m4** [comment]
As for your issue, this is probably a problem with your configuration. If you are running on macOS, check out the following issues: [#13](https://github.com/k4m4/kickthemout/issues/13), [#7](https://github.com/k4m4/kickthemout/issues/7) & [#10](https://github.com/k4m4/kickthemout/issues/10).

**Comment by xdavidhu** [comment]
I have to agree with @k4m4. Please only open an issue if you have a specific problem, which was not solved before in other issues. Thank you.
