### ISSUE TITLE
Not doing anything

### ISSUE THREAD

**Issue by Adesiii** [k4m4/kickthemout#71]
So ive just recently been getting into linux and pentesting etc, and i saw a video on this by JackkTutorials, so i decided to give it a go but unfortunately it doesnt do anything.

im running kali linux 3 and its a live boot from usb on a laptop, ive tried to use it on my android phone to no avail as well as my iphone, and i can still browse the web and use my internet.

i have installed the requirements(it shows they are satisfied with no other errors)

what am i doing wrong?

**Comment by xdavidhu** [comment]
So when you start it, it just hangs and does not show the menu with the KickThemOut logo?

**Comment by BusesCanFly** [comment]
I have the same issue, after running sudo python kickthemout.py, I receive nothing, just an empty line. however, when the command is not run as root, you receive the red and green message telling you to run as root, meaning that kickthemout is present.

**Comment by k4m4** [comment]
Hi there. In a recent commit, we changed the whole scanning process in order to improve usability and resolve issues previously raised. Please try following the new installation procedure.
If this issue still occurs, please let us know.
Thank you.
