### ISSUE TITLE
error with running kickthemout.py

### ISSUE THREAD

**Issue by jbae995** [k4m4/kickthemout#73]
FIRST ERROR:

sudo python kickthemout.py

ERROR: Requirements have not been properly satisfied. Please try running:
	$ sudo pip install -r requirements.txt

If you still get the same error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

JSs-MacBook-Pro:kickthemout jsbae$ sudo pip install -r requirements.txt
The directory '/Users/jsbae/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

SECOND ERROR:

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-NhppFQ/scapy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-afrFKn-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-NhppFQ/scapy/

**Comment by krychevsk16** [comment]
Same for me!

**Comment by k4m4** [comment]
Hi there. Check out the following issues: [#13](https://github.com/k4m4/kickthemout/issues/13), [#7](https://github.com/k4m4/kickthemout/issues/7) & [#10](https://github.com/k4m4/kickthemout/issues/10). Please let me know if this resolves your issue. Thanks.
