### ISSUE TITLE
ERROR: Requirements have not been properly satisfied.

### ISSUE THREAD

**Issue by krychevsk16** [k4m4/kickthemout#74]
ERROR: Requirements have not been properly satisfied. Please try running:
	$ sudo pip install -r requirements.txt

After I already intalled them, still doesn't work.

**Comment by k4m4** [comment]
Hi there. I believe that you are running macOS (correct me if I'm wrong). Check out the following issues: [#13](https://github.com/k4m4/kickthemout/issues/13), [#7](https://github.com/k4m4/kickthemout/issues/7) & [#10](https://github.com/k4m4/kickthemout/issues/10). Please let me know if this resolves your issue. Thanks.
