### ISSUE TITLE
Caching wheels disabled (pip)

### ISSUE THREAD

**Issue by krychevsk16** [k4m4/kickthemout#76]
"The directory '/Users/*name*/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag."

Doesn't work with "sudo -H"

**Comment by k4m4** [comment]
Hey. Again, this has to do with the `pip` config. on your device. Look out for a solution to this issue on stackoverflow. Thanks.

**Comment by krychevsk16** [comment]
What specifically should I search for?

@k4m4

**Comment by k4m4** [comment]
Hi again. I responded to you on the previous issue. @krychevsk16
