### ISSUE TITLE
Code Error 1

### ISSUE THREAD

**Issue by glacialwind** [k4m4/kickthemout#79]
Hi,
I get this error `Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-n9luq3fy/scapy/` after this command ` sudo pip install -r requirements.txt `
I've already installed pip, with -get-pip.py
What's the problem and how to resolve it ?
Thank You

**Comment by k4m4** [comment]
Hey there. Please have a look at [Issue #37](https://github.com/k4m4/kickthemout/issues/37). Let me know if this helped solve your issue. Thanks!

**Comment by glacialwind** [comment]
It didn't
