### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'src'

### ISSUE THREAD

**Issue by 404Ghost99** [k4m4/kickthemout#8]
Hello, i got this error when i running > python kickthemout.py
can u help me? thanks :smile:   

```
File "kickthemout.py", line 291, in <module>
    defaultGatewayIP = getGatewayIP()
  File "kickthemout.py", line 236, in getGatewayIP
    return getGateway_p.src
AttributeError: 'NoneType' object has no attribute 'src'
```

**Comment by k4m4** [comment]
There was a problem while attempting to programmatically obtain the Gateway IP address. We made a few changes to the main script and now allow manual entry for when such errors occur. You should be all set.

**Comment by 404Ghost99** [comment]
ok thanks i'll try it

**Comment by k4m4** [comment]
Let us know if you have any further issues.

**Comment by AndrewOlsen** [comment]
I'm getting an error with as well. I receive this when I run: python2 kickthemout.py

Traceback (most recent call last):
  File "kickthemout.py", line 296, in <module>
    defaultGatewayIP = getGatewayIP()
  File "kickthemout.py", line 239, in getGatewayIP
    print("\n{0}ERROR: Gateway IP could not be obtained. Please enter IP manually.{2}\n").format(RED, END)
IndexError: tuple index out of range

**Comment by xdavidhu** [comment]
Yes, i just fixed that today. Please re-clone it and try again.

**Comment by k4m4** [comment]
It should work now. Thanks for notifying us.

**Comment by k4m4** [comment]
@AndrewOlsen Please let us know if the issue hasn't been resolved.

**Comment by AndrewOlsen** [comment]
This issue has been solves thanks. One last thing, if the IP retrieval doesn't work it doesn't inform me until after I enter the keyboard interrupt. Besides that it is working great.

**Comment by NickKok** [comment]
Hello i have se same problem.
I get 
ERROR: Gateway IP could not be obtained. Please enter IP manually.

kickthemout> Enter Gateway IP (e.g. 192.168.1.1): 
and when i type my Gateway IP (i use "netstat -r -n") nothing happens

**Comment by k4m4** [comment]
So you entered an IP such as 192.168.1.1, correct? @NickKok

**Comment by NickKok** [comment]
yes, i use netstat to chech my gateway and the i write it as your example: 192.168.1.1 and nothinf happened. Do i have to put quotes' '?

**Comment by k4m4** [comment]
No, you don't have to use quotes. I'll work on and let you know when the issue is solved. @NickKok

**Comment by k4m4** [comment]
Please let me know what OS you are running and what you mean by 'nothing happens'. Does the script stop running? @NickKok

**Comment by NickKok** [comment]
i am using linux debian distro.I run the script and then i put the gateway that it asked me and then it finshed and i see the command line again.

**Comment by NickKok** [comment]
~/kickthemout $ python kickthemout.py 

ERROR: Gateway IP could not be obtained. Please enter IP manually.

kickthemout> Enter Gateway IP (e.g. 192.168.1.1): 192.168.1.254
 ~/kickthemout $

**Comment by AndrewOlsen** [comment]
The script needs to be run as root

**Comment by NickKok** [comment]
Thank i had to run pip install -r requirements.txt as root
