### ISSUE TITLE
Can't find urllib2 on Manjaro (archlinux based)

### ISSUE THREAD

**Issue by NourEddineX** [k4m4/kickthemout#80]
$ sudo python kickthemout.py
Traceback (most recent call last):
  File "kickthemout.py", line 13, in <module>
    import urllib2 as urllib
ModuleNotFoundError: No module named 'urllib2'
$ sudo pip install urllib2
Collecting urllib2
  Could not find a version that satisfies the requirement urllib2 (from versions: )
No matching distribution found for urllib2

**Comment by k4m4** [comment]
Hi there. Try running:
```
$ sudo python2 kickthemout.py
```
Let me know if this resolves your issue.
Thanks!

**Comment by NourEddineX** [comment]
It works.. thank you :+1:

**Comment by k4m4** [comment]
Happy to hear so. :) @NourEddineX

**Comment by AJgotBeard** [comment]
@NourEddineX buddy you say Manjaro?
How did you got this working in Manjaro?
I am trying but I can't figure it out and they say they didn't tested on Arch based so they don't care.

**Comment by k4m4** [comment]
@AJgotBeard 
Try `$ sudo python2 kickthemout.py`.
