### ISSUE TITLE
installing kickthemout on mac OS X  ERROR (Im on OS X Sierra 10.12.3) 

### ISSUE THREAD

**Issue by efdhg** [k4m4/kickthemout#81]
I'm trying to install this on my mac, and I ran sudo pip install pcapy which worked and says requirement already satisfied, but when I try to run brew install libdnet scapy it says this and does not install.
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
librdkafka

Error: No available formula with the name "scapy" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
Than I just tried running kickthemout without it, but it just says 
ERROR: Requirements have not been properly satisfied. Please try running:
	$ sudo pip install -r requirements.txt

If you still get the same error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues
I tried running the $ sudo pip install -r requirements.txt  but it just says 
The directory '/Users/andrewshin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/andrewshin/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: scapy in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
so what do I need to do? CAN SOMEBODY PLZ HELP? (any help would be very appreciated.

**Comment by k4m4** [comment]
Hey buddy. Check out [Issue #54](https://github.com/k4m4/kickthemout/issues/54); it should give you the solution to this issue. Let me know if this helps. Thanks!
