### ISSUE TITLE
pip error on Windows

### ISSUE THREAD

**Issue by CrypticGit** [k4m4/kickthemout#82]
Im trying to run install requirements.txt with pip as instructed but still doesn't run after i installed requirements. It works fine on my kali linux box but doesn't on windows or my jailbroken iphone

03/02/2017  02:07 PM    <DIR>          .
03/02/2017  02:07 PM    <DIR>          ..
03/02/2017  02:06 PM            98,153 easy_install-2.7.exe
03/02/2017  02:06 PM            98,153 easy_install.exe
03/02/2017  02:06 PM            98,125 pip.exe
03/02/2017  02:06 PM            98,125 pip2.7.exe
03/02/2017  02:06 PM            98,125 pip2.exe
03/02/2017  02:07 PM             1,501 scapy
03/02/2017  02:07 PM               116 scapy.bat
03/02/2017  02:07 PM             1,528 UTscapy
03/02/2017  02:07 PM               120 UTscapy.bat
03/02/2017  02:06 PM            98,132 wheel.exe
              10 File(s)        592,078 bytes
               2 Dir(s)  109,770,047,488 bytes free

C:\Python27\Scripts>pip install -r C:\Users\541501\Downloads\kto\requirements.tx
t
Requirement already satisfied: scapy in c:\python27\lib\site-packages (from -r C
:\Users\541501\Downloads\kto\requirements.txt (line 1))

C:\Python27\Scripts>pip install -r C:\Users\541501\Downloads\kto\requirements.tx
t
Requirement already satisfied: scapy in c:\python27\lib\site-packages (from -r C
:\Users\541501\Downloads\kto\requirements.txt (line 1))

C:\Python27\Scripts>pip install -r C:\Users\541501\Downloads\kto\requirements.tx
t

C:\Python27\Scripts>cd C:\Users\541501\Downloads\kto

C:\Users\541501\Downloads\kto>dir
 Volume in drive C has no label.
 Volume Serial Number is 5081-9AAE

 Directory of C:\Users\541501\Downloads\kto

03/02/2017  02:05 PM    <DIR>          .
03/02/2017  02:05 PM    <DIR>          ..
03/02/2017  02:01 PM               232 .gitignore
03/02/2017  02:01 PM               121 .travis.yml
03/02/2017  02:01 PM                54 CHANGES.rst
03/02/2017  02:01 PM            16,050 kickthemout.py
03/02/2017  02:01 PM             1,077 LICENSE
03/02/2017  02:05 PM         1,615,467 pip.py
03/02/2017  02:04 PM                 0 pip.txt
03/02/2017  02:01 PM             3,103 README.rst
03/02/2017  02:01 PM                 5 requirements.txt
03/02/2017  02:01 PM             2,381 scan.py
03/02/2017  02:01 PM               880 spoof.py
              11 File(s)      1,639,370 bytes
               2 Dir(s)  109,770,043,392 bytes free

C:\Users\541501\Downloads\kto>python
'python' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\541501\Downloads\kto>py kickthemout.py

←[91mERROR: Requirements have not been properly satisfied. Please try running:
        ←[1;32m$ sudo pip install -r requirements.txt←[0m

←[91mIf you still get the same error, please submit an issue here:
        ←[94mhttps://github.com/k4m4/kickthemout/issues
←[0m

**Comment by k4m4** [comment]
Hi there. KickThemOut has been developed to operate with Windows and Mac OS X operating systems. Windows is not within the compatibility range. I would suggest installing it in a Linux environment. Thanks!
