### ISSUE TITLE
Requirements Issue

### ISSUE THREAD

**Issue by lama1984** [k4m4/kickthemout#84]
Hi this is my problem.Cant open kickthemout.
I have python 2.17.13 Kalilinux gnome version 3.20.2
This is terminal problem
root@kali:~/Downloads/kickthemout-master# python kickthemout.py

ERROR: Requirements have not been properly satisfied. Please try running:
	$ sudo pip install -r requirements.txt

If you still get the same error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

root@kali:~/Downloads/kickthemout-master# sudo pip install -r requirements.txt
Requirement already satisfied: scapy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))

**Comment by k4m4** [comment]
Hey buddy. Check out [Issue #54](https://github.com/k4m4/kickthemout/issues/54); it should give you the solution to this issue. Let me know if this helps. Thanks!
