### ISSUE TITLE
Kickthemout does not work on macOS Sierra (10.12.3)

### ISSUE THREAD

**Issue by Piirtola** [k4m4/kickthemout#86]
I know there is two closed issues about same thing, but the #54 did not work for me. It just gives me this, "sudo echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> ~/Library/Python/2.7/lib/python/site-packages/homebrew.pth
-bash: /Users/rasmuspiirtola/Library/Python/2.7/lib/python/site-packages/homebrew.pth: Permission denied."
Have tried everything uninstalled python and homebrew, but it did not help... I am only account on my mac if you don't count the guest user. Please help.

**Comment by k4m4** [comment]
```
First of all type in your cmd:

pip install scapy
pip install git+git://github.com/hellais/pypcap.git
brew install --with-python libdnet

Then,

mkdir -p ~/Library/Python/2.7/lib/python/site-packages
echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> ~/Library/Python/2.7/lib/python/site-packages/homebrew.pth
```
So you tried this, right?

**Comment by Piirtola** [comment]
The first 3 commands run nicely then the last two didn't run nicely at all...

Rasmuss-MacBook-Air:~ rasmuspiirtola$ sudo mkdir -p ~/Library/Python/2.7/lib/python/site-packages
Password:
Rasmuss-MacBook-Air:~ rasmuspiirtola$ sudo echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> ~/Library/Python/2.7/lib/python/site-packages/homebrew.pth
-bash: /Users/rasmuspiirtola/Library/Python/2.7/lib/python/site-packages/homebrew.pth: Permission denied

And I have tried many times and uninstalled the python and installed it back, but does not work.

**Comment by DominikBucher12** [comment]
Hello, I got simmiliar problem... Installed everything right, running Python 2.7.13, macOS Sierray 10.12(latest)... tried to debug but with no success, will try again tommorow...

Basically the problem is the same, I fire up kickthemout, error occurs, that tool cannot get my Mac bla bla, I insert my macAddress and it gives me error below. I believe it is somehow connected with new macOS and permissions or whatever, but dunno. Thanks in advance :) 

> ERROR: Default Interface MAC Address could not be obtained. Please enter MAC manually.
> 
> kickthemout> Enter MAC Address (MM:MM:MM:SS:SS:SS): AA:AA:AA:AA:AA:AA
> 
> **ERROR: Network scanning failed. Please check your requirements configuration.**

**Comment by k4m4** [comment]
Hi there. In a recent commit, we changed the whole scanning process in order to improve usability and resolve issues previously raised. Please try following the new installation procedure.
If this issue still occurs, please let us know.
Thank you all.

**Comment by DominikBucher12** [comment]
Hello I am sorry, a bit misunderstanding - I tought brew can handle multiple installations at once with: 

$ brew install libdnet scapy nmap

sorry for misunderstanding,  my issues is okay, but dunno about Piirtola. Thanks for being so awesome :)

**Comment by k4m4** [comment]
Thank _you_ for your support. :)
@DominikBucher12
