### ISSUE TITLE
command not found on mac os x

### ISSUE THREAD

**Issue by satorniak49** [k4m4/kickthemout#87]
when i enter  $ sudo pip install pcapy
$ brew install libdnet 
$ brew install scapy 
 that doesn't work
 "command not found"

**Comment by niklaseeeee** [comment]
Did you install homebrew?

**Comment by k4m4** [comment]
Hi there. In a recent commit, we changed the whole scanning process in order to improve usability and resolve issues previously raised. Please try following the new installation procedure.
If this error still occurs, please let us know and we'll re-open the issue.
Thank you.
