### ISSUE TITLE
urllib2  for python3 is duplicate 

### ISSUE THREAD

**Issue by silentcontrole** [k4m4/kickthemout#89]
i think you guys need to update your code to run on python 3.x
+ like changing import urllib2 ;)
+ and add the () in the print hostlist -> print (hostlist) //i'm not really sure of this one

**Comment by R3DDY97** [comment]
@silentcontrole 
i made the code to work with pytohn3 

but dont know how to merge with original version 

i think its better to have two versions

one for who works on Python2.7

others who works on python3

check it out 

[https://github.com/R3DDY97/KICKthemOUT3](url)
