### ISSUE TITLE
Many 'no permission' issues...

### ISSUE THREAD

**Issue by Grayson3197** [k4m4/kickthemout#91]
I have tried installing this many times, and every time, it has failed to install pcapy, scapy, and the other dependencies.

here are some of the errors:
`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-myg48D/pcapy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2uO4Fo-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-myg48D/pcapy/`

`error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted`

`The directory '/Users/user/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/user/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.`

Any help is greatly appreciated. Thanks in advance!

Edit: I am running macOS f you couldn't already tell.

**Comment by k4m4** [comment]
Hi there. Check out the following issues: [#13](https://github.com/k4m4/kickthemout/issues/13), [#7](https://github.com/k4m4/kickthemout/issues/7) & [#10](https://github.com/k4m4/kickthemout/issues/10). Please let me know if this resolves your issue. Thanks.
