### ISSUE TITLE
Requirements have not been properly satisfied...

### ISSUE THREAD

**Issue by ElliotPoots** [k4m4/kickthemout#95]
I've ran: _sudo python -m pip install -r requirements.txt_ and received this error:

The directory '/Users/admin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/admin/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: scapy in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: python-nmap in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 2))

I then ran this command:  _sudo -H python -m pip install -r requirements.txt_ and received:

Requirement already satisfied: scapy in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: python-nmap in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 2))

When running _sudo python kickthemout.py_ I receive:

ERROR: Requirements have not been properly satisfied. Please try running:
	$ sudo pip install -r requirements.txt

If you still get the same error, please submit an issue here:
	https://github.com/k4m4/kickthemout/issues

**Comment by k4m4** [comment]
Hi there. Check out the following issues: [#13](https://github.com/k4m4/kickthemout/issues/13), [#7](https://github.com/k4m4/kickthemout/issues/7) & [#10](https://github.com/k4m4/kickthemout/issues/10). Please let me know if this resolves your issue. Thanks.
