### ISSUE TITLE
Requirements Issue

### ISSUE THREAD

**Issue by KnifeBoss** [k4m4/kickthemout#97]
- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: Manjaro 17.0 (Arch Linux) Cinnamon
- **Python version**: Python 3.6.0
- **Scapy version**: Don't know.
- **Nmap version**: 7.40
- **Link of [Gist](https://gist.github.com/)**: https://gist.github.com/KnifeBoss/b6bb3a385ddb8cb13677a70c8b0ea61f

## Issue

Hello,
When i try to run kickthemout.py I am told Requirements have not been properly satisfied so I run: 

> sudo pip install -r requirements.txt

I get this output.

`Collecting scapy (from -r requirements.txt (line 1))
  Using cached scapy-2.3.3.tgz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5m5xhg_q/scapy/setup.py", line 36
        os.chmod(fname, 0755)
                           ^
    SyntaxError: invalid token
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5m5xhg_q/scapy/
`
I have tried installing scapy from:

> sudo pip install scapy

and get the same error.

I have read Issue #37 but that doesn't seem to fix the issue for me.

**Comment by k4m4** [comment]
Hi there. Have you tried running `$ sudo apt-get update && sudo apt-get install nmap`?
Thanks.

**Comment by KnifeBoss** [comment]
I am not running debian... I wrote I am on Manjaro

**Comment by k4m4** [comment]
Again, thank you for posting an issue. KickThemOut has only been tested with Debian & macOS. The issue you have brought up has to do with `scapy`, not KTO. Thanks.
