### ISSUE TITLE
Network scanning failed

### ISSUE THREAD

**Issue by Madhivarman** [k4m4/kickthemout#98]
ERROR: Network scanning failed. Please check your requirements configuration.
i got an above error while running the python script..I have a python interpretor version 2.7.13 . In the requirement.txt file has two interpretor scap and python nmap.What i have to do to run the script in my debian machine

**Comment by xdavidhu** [comment]
Hey!

Have you installed the dependencies? If not, execute these commands:
```
sudo apt-get update && sudo apt-get install nmap
sudo python -m pip install -r requirements.txt
```
